-- =====================================================================
-- Wynla Season 1 round 2 — ALL migrations for the 2026-09-23 round-2b
-- packages (go + ledger)
-- =====================================================================
--
-- Generated by concatenating handoff-docs/sql/2026-09-23-go.sql and
-- handoff-docs/sql/2026-09-23-ledger.sql, unchanged, in that order. Run
-- it ONCE, in full, in the Supabase SQL editor as the postgres role
-- (Dashboard > SQL Editor > New query > paste > Run). Every statement is
-- idempotent (ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS /
-- CREATE INDEX IF NOT EXISTS / CREATE OR REPLACE VIEW / COMMENT ON), so
-- re-running it is harmless.
--
-- PREREQUISITE: handoff-docs/sql/2026-09-23-ALL-season-1.sql must have
-- run first (PR #49). This file builds on the Season 1 core schema
-- (profiles, digest_subscriptions, resorts, weather_history, cron_runs)
-- and is NOT included in that file.
--
-- Deploy order does not matter: both packages feature-detect their
-- objects (PostgREST 42703 / PGRST205) and degrade gracefully until this
-- has run —
--   * go:     /go works for everyone; the Thursday opt-in saves the city
--             and says the email is coming; the thursday-picks cron
--             exits with reason "profiles.pass_product missing".
--   * ledger: refresh-weather logs one warning (at most every 10 min)
--             and skips the ledger step; /api/health reports
--             ledger.available = false.
--
-- Contents:
--   1. go     — profiles.pass_product (the Thursday list's own consent)
--               + saturday_predictions table (service-role only).
--   2. ledger — prediction_log table + indexes (service-role only) +
--               prediction_log_region_stats view (security_invoker) +
--               a 24-month retention delete (no-op on a fresh table).
-- =====================================================================

-- ###################################################################
-- 1/2  handoff-docs/sql/2026-09-23-go.sql
-- ###################################################################

-- Go package (2026-09-23): "where should I ride this Saturday" — /go page +
-- the Thursday picks email. NOT RUN YET. Idempotent; paste into the
-- Supabase SQL editor once. The app feature-detects both objects
-- (PostgREST 42703 / PGRST205 → graceful fallback, logged once), so the
-- deploy is safe before and after this runs:
--   * before: /go works for everyone (no login), "Email me this every
--     Thursday" tells signed-in users it is coming, the cron exits with
--     reason "profiles.pass_product missing".
--   * after: the opt-in saves city + pass product, the cron sends.
--
-- Depends on: public.profiles (live), public.digest_subscriptions (live).
-- cron_runs (handoff-docs/sql/2026-09-23-ALL-season-1.sql) is optional —
-- it only adds run history and the same-day dedupe.

-- ---------------------------------------------------------------------------
-- 1. profiles.pass_product — which pass product the Thursday email ranks for,
--    and the consent for that list: NOT NULL = on the Thursday list,
--    NULL = not opted in. It is independent of digest_subscriptions.enabled
--    (the weekly favorites digest); the digest row only supplies the
--    address and the id the signed unsubscribe link is minted from, and
--    /api/go/subscribe creates one with enabled = false when the user has
--    none. The Thursday email's unsubscribe link (list=thursday) clears
--    this column and nothing else.
--    Values are "<family>" or "<family>:<productKey>" from lib/passAccess.ts,
--    e.g. "ikon", "ikon:ikon-base-pass", "epic:northeast-value-pass".
--    "any" means no pass (lift tickets). The API validates against the
--    verified dataset before writing, so no CHECK constraint here: product
--    keys change every season and a constraint would need a migration each
--    time.
-- ---------------------------------------------------------------------------
alter table public.profiles
  add column if not exists pass_product text;

comment on column public.profiles.pass_product is
  'Thursday picks email: pass family[:productKey] to rank for (lib/passAccess.ts keys, or "any"). NOT NULL = on the list, NULL = not opted in. Set by /api/go/subscribe, cleared by DELETE or the list=thursday unsubscribe link. Independent of digest_subscriptions.enabled.';

-- The existing owner-only RLS policies on profiles cover the new column.
-- The service role (cron, unsubscribe route) bypasses RLS as usual.

-- ---------------------------------------------------------------------------
-- 2. saturday_predictions — what we told whom, so the picks can be scored
--    against what actually happened (strategy 2026-09-18: collect
--    prediction data silently from day one). One row per (origin, pass
--    product, target date) per cron run; the page does not write here.
--    Service-role only: RLS on, no policies.
-- ---------------------------------------------------------------------------
create table if not exists public.saturday_predictions (
  id            bigint generated always as identity primary key,
  made_at       timestamptz not null default now(),
  source        text not null default 'thursday-picks',   -- cron job / page
  origin_code   text not null,                            -- lib/origins.ts code
  pass_product  text not null,                            -- same vocabulary as profiles.pass_product
  target_date   date not null,
  horizon_days  smallint not null,
  mode          text not null,                            -- picks | no-picks | off-season | none
  -- Top picks + runners-up as the ranking produced them: slug, score,
  -- breakdown, expected snow, surface code + confidence, drive seconds,
  -- confidence tag. Enough to grade later without re-running old inputs.
  picks         jsonb not null,
  recipients    integer not null default 0
);

create index if not exists saturday_predictions_target_idx
  on public.saturday_predictions (target_date, origin_code, pass_product);

alter table public.saturday_predictions enable row level security;

comment on table public.saturday_predictions is
  'Saturday picks as sent (Thursday email) for later verification against measured snow and reported surface. Service role writes; nothing reads yet.';

-- ---------------------------------------------------------------------------
-- 3. Optional: drive_time_cache rows for the new launch cities. The /go
--    page (and the map) estimate drive times ("≈") for Washington DC,
--    Chicago, Minneapolis and Detroit until the cache job
--    (scripts/compute-drive-times.mjs) is run with origin_name set to
--    the exact `name` strings in lib/origins.ts ORIGINS ("Washington",
--    "Chicago", "Minneapolis", "Detroit" — note DC's name is plain
--    "Washington" since the round-2 integration). Once rows exist, flip
--    `cached` to true on those entries (the last argument of city())
--    so both surfaces read them. Philadelphia is listed as cached in
--    lib/origins.ts but had no rows on 2026-09-23; the loader falls
--    back to the estimate when the query returns nothing.
-- ---------------------------------------------------------------------------

-- ###################################################################
-- 2/2  handoff-docs/sql/2026-09-23-ledger.sql
-- ###################################################################

-- Wynla prediction ledger — 2026-09-23
-- Idempotent. Run in the Supabase SQL editor (service role / owner).
-- The application feature-detects this table (lib/predictionLog.ts) and
-- degrades gracefully when it is missing: refresh-weather logs one
-- warning per process and skips the ledger step, /api/health reports
-- ledger.available = false. It can be applied before or after the code
-- deploys.
--
-- What it stores: every surface-forecast call and forecast number the
-- pipeline makes for a resort-day, frozen at the moment it is made, and
-- later the observed value for that same day plus a hit/miss verdict.
-- One row per (resort, target day, horizon): the same Saturday is
-- predicted several times as it approaches, and each of those is its
-- own row so accuracy can be reported per horizon. A row is inserted
-- once and never overwritten (ON CONFLICT DO NOTHING in the writer):
-- made_at is the first forecast of that resort-local day.
--
-- No public UI reads this in season 1. See
-- handoff-docs/PREDICTION_LEDGER_2026-09-23.md for what may be claimed
-- publicly and when.

create table if not exists public.prediction_log (
  id                  bigserial primary key,
  resort_id           bigint      not null references public.resorts (id) on delete cascade,
  for_date            date        not null,   -- resort-local calendar day the prediction is about
  made_at             timestamptz not null,   -- when the prediction was frozen
  horizon_days        smallint    not null,   -- 0 = same day, 1 = tomorrow, n = n days ahead
  -- the prediction
  surface_class       text,                   -- SANY code from lib/snowSurface, null when dormant
  surface_confidence  text,                   -- 'low' | 'medium' | 'high'
  forecast_snow_in    numeric,                -- base-elevation snowfall for the day
  forecast_high_f     integer,
  forecast_low_f      integer,
  forecast_gust_mph   integer,
  source              jsonb,                  -- provenance: forecast source, updated_at, coverage
  -- what happened (filled by the scorer)
  actual_snow_in      numeric,
  actual_high_f       integer,
  actual_low_f        integer,
  actual_gust_mph     integer,
  actual_surface_class text,                  -- classifier re-run on OBSERVED inputs only
  actual_source       jsonb,
  scored_at           timestamptz,
  surface_hit         boolean,                -- null when either class is missing
  snow_abs_err_in     numeric,
  constraint prediction_log_unique unique (resort_id, for_date, horizon_days),
  constraint prediction_log_horizon_chk check (horizon_days between 0 and 16),
  constraint prediction_log_confidence_chk
    check (surface_confidence is null or surface_confidence in ('low', 'medium', 'high'))
);

-- Scorer: "rows for this day that are not scored yet".
create index if not exists prediction_log_for_date_unscored_idx
  on public.prediction_log (for_date)
  where scored_at is null;

-- /api/health counts: logged in the last 24 h, scored in the last 7 d.
create index if not exists prediction_log_made_at_idx
  on public.prediction_log (made_at desc);
create index if not exists prediction_log_scored_at_idx
  on public.prediction_log (scored_at desc)
  where scored_at is not null;

-- Scorer, scheduled path: "oldest unscored target day" (partial index
-- above) and keyset pages by id inside one day.
create index if not exists prediction_log_for_date_id_unscored_idx
  on public.prediction_log (for_date, id)
  where scored_at is null;

-- Service role only. No policies on purpose: the ledger is written and
-- read by the crons with the service key; nothing user-facing reads it
-- until the founder has reviewed the numbers (see the handoff doc).
alter table public.prediction_log enable row level security;

-- Founder gate: compared / hit counts per region and horizon, all time,
-- rows with a verdict only (dormant, closed and unobserved rows have a
-- null surface_hit and never count). Read by /api/health when the
-- request carries the cron bearer token; feature-detected like the
-- table. security_invoker so the anon role, which has no policy on the
-- table, sees nothing through the view either.
create or replace view public.prediction_log_region_stats
  with (security_invoker = true) as
select r.region,
       p.horizon_days,
       count(*)::int                             as compared,
       count(*) filter (where p.surface_hit)::int as hits
from public.prediction_log p
join public.resorts r on r.id = p.resort_id
where p.surface_hit is not null
group by r.region, p.horizon_days;

-- Retention: keep two seasons. Run by hand each summer, or with pg_cron:
--   select cron.schedule('prune-prediction-log', '0 3 1 7 *',
--     $$delete from public.prediction_log where for_date < now() - interval '24 months'$$);
delete from public.prediction_log where for_date < now() - interval '24 months';
