-- =====================================================================
-- Wynla Season 1 core — ALL migrations for the 2026-09-23 package round
-- =====================================================================
--
-- Generated by concatenating handoff-docs/sql/2026-09-23-{install,alerts,
-- planner,pipeline,hygiene}.sql in a safe order. Run it ONCE, in full, in
-- the Supabase SQL editor as the postgres role (Dashboard > SQL Editor >
-- New query > paste > Run). Every statement is idempotent (IF NOT EXISTS /
-- DROP POLICY IF EXISTS / catalog lookups), so re-running it is harmless.
--
-- Order and why:
--   1. install  — push_subscriptions UPDATE policy (first version).
--   2. alerts   — re-creates the SAME policy with the reviewed, stricter
--                 WITH CHECK (a signed-in user can claim an anonymous row
--                 but the row must end up owned by them). Because it runs
--                 after the install section, the alerts definition is the
--                 one that stays. Also adds two small indexes.
--   3. planner  — trips.start_date (the app feature-detects the column).
--   4. pipeline — cron_runs (run history + founder-alert dedupe; the crons
--                 feature-detect it), weather_cache index, prune.
--   5. hygiene  — trip_shares: drops the public SELECT policy (anon token
--                 enumeration), owner-only policies, FK ON DELETE CASCADE,
--                 unique token index. PREREQUISITE: SUPABASE_SERVICE_ROLE_KEY
--                 must be set in Vercel for /trip/share/[token] to keep
--                 resolving links after this runs.
--
-- The app code (feat/season-1-core) works before AND after this file is
-- applied; what it unlocks: re-enabling push alerts on the same device,
-- trip start dates, cron run history + /api/health details + founder
-- alert emails, and the trip-share hardening.
--
-- After running: regenerate handoff-docs/DB_SCHEMA_LIVE_2026-09-23.md
-- (see its header) so the schema doc matches the live project.
-- =====================================================================

-- ---------------------------------------------------------------------
-- [install] Install package — push_subs_update_own (first definition; superseded by the alerts section below, kept so the file matches the package doc)
-- (source: handoff-docs/sql/2026-09-23-install.sql)
-- ---------------------------------------------------------------------
-- 2026-09-23 — install package (one-tap install + installed-app polish).
--
-- push_subscriptions has SELECT / INSERT / DELETE policies only
-- (data/stage-29-schema.sql). /api/push/subscribe upserts by endpoint, so
-- re-POSTing an existing subscription — which PwaRegistrar now does once
-- per session for signed-in users to keep last_seen_at fresh and to bind
-- a row the service worker re-created while signed out — hits the
-- ON CONFLICT ... DO UPDATE path and is denied without an UPDATE policy.
--
-- Idempotent: safe to run more than once. Run in the Supabase SQL editor
-- as the postgres role.

BEGIN;

DROP POLICY IF EXISTS "push_subs_update_own" ON push_subscriptions;
CREATE POLICY "push_subs_update_own" ON push_subscriptions FOR UPDATE
  -- A signed-in user may update their own rows and claim anonymous ones;
  -- the new row must still be theirs (or stay anonymous). Nobody can
  -- reassign a row to a different user or strip another user's ownership.
  USING (auth.uid() = user_id OR user_id IS NULL)
  WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

COMMIT;

-- ---------------------------------------------------------------------
-- [alerts] Alerts + digest package — push_subs_update_own (FINAL definition: TO authenticated, WITH CHECK auth.uid() = user_id) + indexes
-- (source: handoff-docs/sql/2026-09-23-alerts.sql)
-- ---------------------------------------------------------------------
-- Snow alerts + digest package (2026-09-23). Idempotent; run once in the
-- Supabase SQL editor. The app works before AND after this runs:
--   * /api/push/subscribe already writes with the service role after
--     verifying ownership, so the missing UPDATE policy no longer blocks
--     re-enabling alerts on a device. The policy below makes the RLS path
--     (used when SUPABASE_SERVICE_ROLE_KEY is absent) work too and is the
--     correct long-term shape.
--   * Nothing else in this package needs new tables or columns: the
--     one-click unsubscribe token is an HMAC over digest_subscriptions.id,
--     and per-day alert dedupe uses the existing snow_alerts.last_alerted_at.

-- push_subscriptions had SELECT / INSERT / DELETE policies only. A
-- supabase-js upsert is INSERT ... ON CONFLICT DO UPDATE, and Postgres
-- evaluates UPDATE policies on the conflict path, so the second enable on
-- the same browser (endpoint already stored) was rejected under RLS.
--
-- Scope: signed-in users only (TO authenticated), so the anon role cannot
-- rewrite legacy NULL-user rows through the public REST endpoint. USING
-- lets the caller take over their own rows and not-yet-claimed (NULL
-- user) rows; WITH CHECK requires the row to end up owned by the caller,
-- so a user can neither hand a row to someone else nor un-claim it back
-- to NULL.
DROP POLICY IF EXISTS "push_subs_update_own" ON public.push_subscriptions;
CREATE POLICY "push_subs_update_own" ON public.push_subscriptions
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id OR user_id IS NULL)
  WITH CHECK (auth.uid() = user_id);

-- The push cron fans out by user; the digest cron looks up rows by id for
-- one-click unsubscribe. Both are tiny tables today, but the indexes cost
-- nothing and keep the crons flat as subscribers grow.
CREATE INDEX IF NOT EXISTS push_subscriptions_user_idx
  ON public.push_subscriptions (user_id);
CREATE INDEX IF NOT EXISTS snow_alerts_enabled_resort_idx
  ON public.snow_alerts (resort_id)
  WHERE enabled;

-- ---------------------------------------------------------------------
-- [planner] Planner package — trips.start_date (+ optional 30-day constraint, commented out)
-- (source: handoff-docs/sql/2026-09-23-planner.sql)
-- ---------------------------------------------------------------------
-- Trip planner package (2026-09-23) — trip dates + day-count constraint.
-- Run once in the Supabase SQL editor. Every statement is idempotent.
--
-- The app feature-detects everything here, so it works before AND after
-- this runs:
--   * trips.start_date — the planner review sheet and the trip page show
--     an optional "Trip start date" field. If the column is missing the
--     insert/update fails with 42703 / PGRST204, the app retries without
--     the field and hides it. Calendar export then anchors day 1 to today
--     and says so.
--   * total_days check — the planner clamps trips to 14 days to match the
--     live constraint. Section 2 (optional) raises it to 30.
--
-- No RLS changes needed: the existing owner-only policies on public.trips
-- cover the new column automatically.

-- 1. Optional planned start date (a calendar day, no time zone). Null means
--    "not decided yet"; the trip page keeps working exactly as before.
alter table public.trips
  add column if not exists start_date date;

comment on column public.trips.start_date is
  'Planned first ski day (local calendar date). Null = undated trip.';

-- 2. OPTIONAL — allow trips up to 30 days. The planner ships clamped to 14
--    because that is what the live constraint allows. If you run this
--    block, also raise MAX_TRIP_DAYS in components/Map/TripPlannerPanel.tsx
--    to 30 so the stepper lets users go past 14.
--
-- alter table public.trips drop constraint if exists trips_total_days_check;
-- alter table public.trips
--   add constraint trips_total_days_check
--   check (total_days between 1 and 30);

-- ---------------------------------------------------------------------
-- [pipeline] Pipeline package — cron_runs table + weather_cache.fetched_at index + 90-day prune
-- (source: handoff-docs/sql/2026-09-23-pipeline.sql)
-- ---------------------------------------------------------------------
-- Wynla data pipeline — 2026-09-23
-- Idempotent. Run in the Supabase SQL editor (service role / owner).
-- The application feature-detects every object below and degrades
-- gracefully when it is missing, so this can be applied before or after
-- the code deploys.

-- 1. Run history for every cron (written by lib/cronRun.ts, read by
--    /api/health). Also holds the 'health-alert' rows used to send the
--    founder at most one alert email per 12 hours — founder alert emails
--    are only sent once this table exists (no table, no durable dedupe,
--    no mail; /api/health still answers 503 when the data is stale).
create table if not exists public.cron_runs (
  id           bigserial primary key,
  job          text        not null,
  started_at   timestamptz not null default now(),
  finished_at  timestamptz,
  ok           boolean,
  duration_ms  integer,
  summary      jsonb,
  error        text
);

create index if not exists cron_runs_job_started_idx
  on public.cron_runs (job, started_at desc);

-- Service role only. No policies on purpose: anon/authenticated users
-- have no reason to read run logs, and the health endpoint aggregates
-- them server-side with the service key.
alter table public.cron_runs enable row level security;

-- 2. Freshness queries in /api/health and the stalest-first ordering in
--    refresh-weather sort by fetched_at; the table is small, but the
--    index keeps the health endpoint instant as history grows.
create index if not exists weather_cache_fetched_at_idx
  on public.weather_cache (fetched_at);

-- 3. Keep run history bounded: delete rows older than 90 days.
--    Run this by hand every few months, or schedule it with pg_cron:
--    select cron.schedule('prune-cron-runs', '0 3 * * 0',
--      $$delete from public.cron_runs where started_at < now() - interval '90 days'$$);
delete from public.cron_runs where started_at < now() - interval '90 days';

-- ---------------------------------------------------------------------
-- [hygiene] Hygiene package — trip_shares owner-only policies, FK cascade, token index (two transactions)
-- (source: handoff-docs/sql/2026-09-23-hygiene.sql)
-- ---------------------------------------------------------------------
-- 2026-09-23 — hygiene package (audit finding security-3: trip share links)
--
-- Run in the Supabase SQL editor as the postgres role. Idempotent: safe to
-- run more than once. Two transactions: part 1 (RLS policies) commits on
-- its own so the FK/index work in part 2 can never roll it back.
--
-- WHY: trip_shares held a public SELECT policy so the share page could
-- resolve a token with the anon key. app/trip/share/[token]/page.tsx now
-- reads (and bumps view_count) through the SERVICE-ROLE client, which
-- bypasses RLS entirely, so anon/authenticated users no longer need to
-- read other people's rows. Leaving the public policy in place lets any
-- signed-out client enumerate every share token with one PostgREST call
-- (GET /rest/v1/trip_shares?select=share_token), which turns "anyone with
-- the link" into "anyone at all".
--
-- After this migration:
--   SELECT  owner only (created_by = auth.uid())   -> TripShareButton can
--                                                    still find its own row
--   INSERT  owner only (created_by = auth.uid())   -> unchanged behaviour
--   DELETE  owner only (created_by = auth.uid())   -> 'Stop sharing' UI
--                                                    (planner package)
--   service_role                                   -> bypasses RLS, share
--                                                    page keeps working
--
-- PREREQUISITE: SUPABASE_SERVICE_ROLE_KEY must be set in Vercel for every
-- environment that serves /trip/share/[token]. The page falls back to the
-- anon client when the key is missing, and with this policy that fallback
-- returns 404 for every share link.

begin;

alter table public.trip_shares enable row level security;

-- Drop every existing policy on the table, whatever it was named, so we
-- end up with exactly the three below regardless of dashboard history.
do $$
declare
  p record;
begin
  for p in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'trip_shares'
  loop
    execute format('drop policy if exists %I on public.trip_shares', p.policyname);
  end loop;
end $$;

create policy "trip_shares_select_owner"
  on public.trip_shares
  for select
  to authenticated
  using (created_by = auth.uid());

create policy "trip_shares_insert_owner"
  on public.trip_shares
  for insert
  to authenticated
  with check (
    created_by = auth.uid()
    and exists (
      select 1 from public.trips t
      where t.id = trip_shares.trip_id and t.user_id = auth.uid()
    )
  );

create policy "trip_shares_delete_owner"
  on public.trip_shares
  for delete
  to authenticated
  using (created_by = auth.uid());

commit;

-- ---------------------------------------------------------------------
-- Part 2: FK cascade + token index. Deliberately a SEPARATE transaction
-- so that if anything here fails (e.g. a constraint name we did not
-- anticipate) the RLS fix above has already committed and the public
-- SELECT policy is gone regardless.
-- ---------------------------------------------------------------------
begin;

-- Orphans: share rows whose trip was deleted while no cascade existed.
-- ADD CONSTRAINT validates existing rows, so these must go first or the
-- constraint fails. They are dead links anyway (share page 404s on them).
delete from public.trip_shares s
where not exists (select 1 from public.trips t where t.id = s.trip_id);

-- Drop the existing FK on trip_id by looking it up rather than assuming
-- the name: a dashboard-created constraint may be called anything, and
-- dropping only "trip_shares_trip_id_fkey" would leave two FKs behind.
do $$
declare
  c text;
begin
  for c in
    select con.conname
    from pg_constraint con
    where con.conrelid = 'public.trip_shares'::regclass
      and con.contype = 'f'
      and con.conkey = array[(
        select att.attnum from pg_attribute att
        where att.attrelid = 'public.trip_shares'::regclass
          and att.attname = 'trip_id'
      )]
  loop
    execute format('alter table public.trip_shares drop constraint %I', c);
  end loop;
end $$;

alter table public.trip_shares
  add constraint trip_shares_trip_id_fkey
  foreign key (trip_id) references public.trips (id) on delete cascade;

-- Token lookups from the share page hit share_token directly; make sure
-- it is unique + indexed (no-op if the dashboard already created it).
create unique index if not exists trip_shares_share_token_key
  on public.trip_shares (share_token);

commit;

-- Verify:
--   1. Expect exactly three rows, none with roles {public} or {anon}:
--      select policyname, roles, cmd from pg_policies
--      where tablename = 'trip_shares' order by policyname;
--   2. Expect exactly one FK, with confdeltype = 'c' (cascade):
--      select conname, confdeltype from pg_constraint
--      where conrelid = 'public.trip_shares'::regclass and contype = 'f';

