-- Pass access package (2026-09-23). DRAFT, NOT RUN. The app ships the same
-- data as a committed JSON file (lib/data/passAccess.json, generated by
-- scripts/build-pass-access.mjs) and reads it with lib/passAccess.ts. This
-- table is the shape to move to once pass rules need to change without a
-- deploy (in-season blackout updates, a founder edit from an admin page,
-- or a cron that re-verifies weekly). Idempotent; run once in the Supabase
-- SQL editor when that day comes, then teach lib/passAccess.ts to prefer
-- the table when it exists (feature-detect: SELECT 1 FROM
-- information_schema.tables WHERE table_name = 'resort_pass_access').
--
-- One row per resort x pass family x product. The JSON's parsed shapes are
-- stored as jsonb (days, blackouts) so the parser stays in one place
-- (scripts/build-pass-access.mjs) and the table never disagrees with the
-- file about what "Dec 26-30 2026" means.

CREATE TABLE IF NOT EXISTS public.resort_pass_access (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  resort_id        bigint NOT NULL REFERENCES public.resorts (id) ON DELETE CASCADE,
  -- Denormalised for readable queries and for the JSON regeneration path
  -- (the app keys everything by slug).
  slug             text   NOT NULL,
  season           text   NOT NULL DEFAULT '2026-27',
  -- Same vocabulary as resorts.passes[]: epic | ikon | indy | mountain_collective
  pass_family      text   NOT NULL CHECK (pass_family IN ('epic', 'ikon', 'indy', 'mountain_collective')),
  product          text   NOT NULL,                 -- "Ikon Base Pass"
  product_key      text   NOT NULL,                 -- "ikon-base-pass"
  -- Part of the unique key, so it cannot be NULL: Postgres treats NULLs as
  -- distinct in a unique constraint and an upsert would insert duplicates
  -- for every row without a qualifier. The loader writes '' for none.
  qualifier        text   NOT NULL DEFAULT '',      -- "All / 32 / 22 Resorts tiers"
  -- Parsed days: {text, kind, short, count?, min?, max?, qualifier?}
  days             jsonb  NOT NULL,
  -- Parsed blackouts: {status, text, ranges: [[start,end]], weekdays: [], rangesSource, lastSeason, scope, note}
  blackouts        jsonb  NOT NULL,
  -- Flat copies of the two facts the map filter will want to index.
  days_kind        text   NOT NULL,                 -- unlimited | limited | range | none | discount | weekdays | other
  blackout_status  text   NOT NULL,                 -- none | dates | weekdays | conditional | unpublished | unknown | not_applicable
  reservation_required boolean NOT NULL DEFAULT false,
  is_bonus_mountain    boolean NOT NULL DEFAULT false,
  shared_with      text,                            -- "Killington and Pico"
  new_for_season   boolean NOT NULL DEFAULT false,
  source_urls      text[] NOT NULL DEFAULT '{}',
  verified_on      date   NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (resort_id, season, pass_family, product_key, qualifier)
);

-- The resort page reads one slug; the map filter reads one family.
CREATE INDEX IF NOT EXISTS resort_pass_access_slug_idx
  ON public.resort_pass_access (slug, season);
CREATE INDEX IF NOT EXISTS resort_pass_access_family_idx
  ON public.resort_pass_access (pass_family, season);

-- Public read (the same data is public on the resort page); writes stay
-- with the service role until an admin page exists.
ALTER TABLE public.resort_pass_access ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "resort_pass_access_public_read" ON public.resort_pass_access;
CREATE POLICY "resort_pass_access_public_read" ON public.resort_pass_access
  FOR SELECT
  USING (true);

-- Keep updated_at honest without relying on the writer.
CREATE OR REPLACE FUNCTION public.resort_pass_access_touch()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS resort_pass_access_touch ON public.resort_pass_access;
CREATE TRIGGER resort_pass_access_touch
  BEFORE UPDATE ON public.resort_pass_access
  FOR EACH ROW EXECUTE FUNCTION public.resort_pass_access_touch();

-- Load path (later): a small script maps lib/data/passAccess.json to rows,
-- resolving resort_id from resorts.slug, writing '' when qualifier is null,
-- and upserts on the UNIQUE key (ON CONFLICT (resort_id, season,
-- pass_family, product_key, qualifier) DO UPDATE).
-- Verify after loading:
--   SELECT pass_family, count(DISTINCT slug) AS resorts, count(*) AS rows
--   FROM public.resort_pass_access WHERE season = '2026-27'
--   GROUP BY 1 ORDER BY 1;
-- Expected on 2026-09-23: epic 37 / 222, ikon 56 / 168, indy 140 / 554,
-- mountain_collective 16 / 16 (matches the JSON and resorts.passes[]).
