import type { Metadata, Viewport } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import PwaRegistrar from "@/components/PwaRegistrar";
import InstallPrompt from "@/components/InstallPrompt";
import AppTabBar from "@/components/AppTabBar";
import GuestFavoritesSync from "@/components/auth/GuestFavoritesSync";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://wynla.app";

// CSS px size + pixel ratio of every iPhone class we ship a launch image
// for. Mirrors IOS_SPLASH_SIZES in scripts/gen-brand-rasters.mjs.
const IOS_SPLASH_SIZES: ReadonlyArray<{ w: number; h: number; dpr: number }> = [
  { w: 440, h: 956, dpr: 3 },
  { w: 402, h: 874, dpr: 3 },
  { w: 430, h: 932, dpr: 3 },
  { w: 393, h: 852, dpr: 3 },
  { w: 428, h: 926, dpr: 3 },
  { w: 390, h: 844, dpr: 3 },
  { w: 375, h: 812, dpr: 3 },
  { w: 414, h: 896, dpr: 3 },
  { w: 414, h: 896, dpr: 2 },
  { w: 375, h: 667, dpr: 2 },
];

// Runs before hydration: Chromium fires `beforeinstallprompt` as soon as
// the install criteria pass, often before React has mounted anything, so
// a listener added in a useEffect would miss it and the one-tap Install
// button would never light up. The event is stashed on window and
// components/InstallPrompt.tsx replays it inside a user gesture.
const INSTALL_CAPTURE_SCRIPT = `window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();window.__wynlaInstallEvent=e;window.dispatchEvent(new Event('wynla:installable'))});window.addEventListener('appinstalled',function(){window.__wynlaInstallEvent=null;window.dispatchEvent(new Event('wynla:installed'))});`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Wynla — Free for the inaugural ski season.",
    template: "%s · Wynla",
  },
  description:
    "Every US ski resort on one map, with pass info, drive time, weather, and the snow surface forecast. Free for the inaugural 2026-27 season — founder pricing locked forever for early members.",
  applicationName: "Wynla",
  manifest: "/manifest.json",
  // NOTE: no `alternates.canonical` here — a canonical set in the root
  // layout cascades to EVERY route, which told Google all ~480 pages were
  // duplicates of the homepage (mass de-indexing risk, caught in the
  // 2026-06-28 live sweep). The homepage sets its own canonical in
  // app/page.tsx; SEO pages set theirs in their generateMetadata.
  appleWebApp: {
    capable: true,
    title: "Wynla",
    // black-translucent → the iOS status bar (clock, battery, signal)
    // overlays our navy header instead of pushing the app content down
    // behind an opaque white bar. Pair with `padding-top:
    // env(safe-area-inset-top)` on whatever sits at the top of each
    // route so the notch / Dynamic Island doesn't eat real content.
    statusBarStyle: "black-translucent",
    // iOS only shows a launch image whose pixel size exactly matches the
    // device AND whose <link media> matches, so there is one file per
    // iPhone class. Generated by scripts/gen-brand-rasters.mjs
    // (IOS_SPLASH_SIZES) — keep the two lists in sync. Devices not
    // listed fall back to the manifest's navy background_color.
    startupImage: IOS_SPLASH_SIZES.map(({ w, h, dpr }) => ({
      url: `/splash/${w * dpr}x${h * dpr}.png`,
      media: `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`,
    })),
  },
  openGraph: {
    type: "website",
    siteName: "Wynla",
    title: "Wynla — Free for the inaugural ski season.",
    description:
      "Every US ski resort on one map. Snow surface forecast, drive time, pass info. Free for the inaugural 2026-27 season.",
    url: SITE_URL,
    images: [{ url: "/og-home.png", width: 1200, height: 630, alt: "Wynla — US ski resort map" }],
  },
  // Card type ONLY — no title/description/images here. A full twitter
  // block in the root layout cascades over every page that doesn't define
  // its own, so resort shares on X were showing the generic homepage card
  // instead of the per-resort dynamic image. With just `card`, X falls
  // back to each page's og:title/og:image (per-resort file-convention
  // image included), which is exactly what we want.
  twitter: {
    card: "summary_large_image",
  },
  icons: {
    icon: [
      { url: "/icon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
  themeColor: "#1E2952",
};

const ORG_JSONLD = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Wynla",
  url: SITE_URL,
  logo: `${SITE_URL}/icon-512.png`,
  description:
    "Wynla is a US ski resort discovery + multi-stop trip planner with a first-of-its-kind snow surface forecast. Free for the inaugural 2026-27 season; founder pricing locked forever for early members.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      // Phone tab bar visibility flag for app/globals.css. Shipped as
      // "1" so the first paint already reserves the bar's height;
      // components/AppTabBar.tsx flips it on routes without the bar.
      data-tab-bar="1"
    >
      <head>
        <link rel="preconnect" href="https://api.mapbox.com" />
        <link rel="preconnect" href="https://events.mapbox.com" />
        <link rel="dns-prefetch" href="https://a.tiles.mapbox.com" />
        <link rel="dns-prefetch" href="https://b.tiles.mapbox.com" />
        <script dangerouslySetInnerHTML={{ __html: INSTALL_CAPTURE_SCRIPT }} />
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: JSON.stringify(ORG_JSONLD) }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:z-[100] focus:rounded focus:bg-wn-navy focus:px-3 focus:py-2 focus:text-sm focus:font-semibold focus:text-white focus:outline-none focus:ring-2 focus:ring-wn-gold"
        >
          Skip to main content
        </a>
        {/* Wrap children so the skip link's #main-content target exists on
            every route. Pages render their own <main>, so this is a div (a
            nested <main> would be invalid); tabIndex makes it focusable so
            the keyboard bypass actually moves focus. */}
        <div id="main-content" tabIndex={-1}>
          {children}
        </div>
        {/* Global legal footer. `mt-auto` plus the body's flex column keeps
            it at the very bottom without pushing the map page (the map
            fills the viewport; the footer sits below the fold for that
            route). Kept tiny so it never competes with primary UI. */}
        <footer className="mt-auto flex flex-col items-center gap-1 px-4 py-3 text-[11px] text-wn-charcoal/55">
          <div className="flex flex-wrap items-center justify-center gap-x-3 gap-y-1">
            <Link href="/early" className="font-semibold text-wn-navy hover:text-wn-navy/80">
              Founder list
            </Link>
            <span aria-hidden="true">·</span>
            <Link href="/go" className="hover:text-wn-navy">
              Where to ride Saturday
            </Link>
            <span aria-hidden="true">·</span>
            <Link href="/trip-templates" className="hover:text-wn-navy">
              Trip ideas
            </Link>
            <span aria-hidden="true">·</span>
            <Link href="/data-sources" className="hover:text-wn-navy">
              Data sources
            </Link>
            <span aria-hidden="true">·</span>
            <Link href="/privacy" className="hover:text-wn-navy">
              Privacy
            </Link>
            <span aria-hidden="true">·</span>
            <Link href="/terms" className="hover:text-wn-navy">
              Terms
            </Link>
            <span aria-hidden="true">·</span>
            <a
              href="mailto:hello@wynla.app"
              className="hover:text-wn-navy"
            >
              Contact
            </a>
          </div>
          {/* FTC affiliate disclosure — required wherever Wynla
              deep-links to a partner that pays commission. Currently
              that's Booking.com + Vrbo on the resort detail page; if
              the affiliate surface ever expands, the disclosure stays
              valid because it covers "partner links" generically. */}
          <p className="max-w-md text-center text-[10px] text-wn-charcoal/45">
            Wynla may earn a commission from purchases made through
            partner links, at no extra cost to you.
          </p>
          <p className="mt-1 text-[10px] text-wn-charcoal/40">
            &copy; {new Date().getFullYear()} Wynla. All rights reserved.
          </p>
        </footer>
        <PwaRegistrar />
        <InstallPrompt />
        {/* Phone-only bottom tabs (Map / Today / Trips / Account). */}
        <AppTabBar />
        {/* Merges hearts saved before sign-in into the account; renders
            nothing and makes no request unless a device list exists. */}
        <GuestFavoritesSync />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
