// Step 3 of the resort photo pipeline: publish the photos the vetting pass
// chose. NOT RUN in the 2026-09-23 package; it is the step that follows the
// human + vision vetting described in handoff-docs/PHOTOS_2026-09-23.md.
//
//   node scripts/photos/3-publish.mjs --chosen .tmp-photo-candidates/chosen.json [--confirm]
//
// Input: chosen.json, one entry per resort:
//   [{ "slug": "alta", "index": 2, "reason": "lift + fresh snow, no faces" }, ...]
//   `index` is the cand-N number in .tmp-photo-candidates/<slug>/manifest.json.
//
// For each entry it:
//   1. Re-reads the candidate's licence from the manifest and refuses
//      anything outside {CC0, public domain, CC BY, CC BY-SA}.
//   2. Crops the 1280 px thumb to 16:9 (attention-based crop, centre
//      fallback), resizes to 1600 wide, JPEG q82.
//   3. With --confirm: uploads to the public bucket resort-heroes as
//      <slug>.jpg (x-upsert, 1-year cache). Without it: writes the JPEG to
//      .tmp-photo-candidates/publish-preview/<slug>.jpg only.
//   4. Appends an UPDATE statement to scripts/photos/reports/publish-<date>.sql
//      and merges {title, sourcePage} into lib/data/heroCredits.json.
//
// It never runs SQL. The generated file is applied by a human in the
// Supabase SQL editor after a last look (hero_image_* columns are the
// vetting pass's to change, per the 2026-09-23 package rules).

import sharp from "sharp";
import { existsSync, mkdirSync, writeFileSync, appendFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { loadEnv, ensurePublicBucket, uploadObject, readJsonIfExists, writeJson, parseArgs, makeLogger, REPORTS_DIR } from "./_shared.mjs";

const OUT_DIR = resolve(".tmp-photo-candidates");
const PREVIEW_DIR = join(OUT_DIR, "publish-preview");
const CREDITS_JSON = resolve("lib/data/heroCredits.json");
const BUCKET = "resort-heroes";
const ALLOWED_LICENCE = /^(CC0|Public domain|PD|CC[ -]BY(-SA)?(\s|$|[ -]\d))/i;
const FORBIDDEN_LICENCE = /\b(NC|ND)\b/i;

const args = parseArgs();
const env = loadEnv();
const logger = makeLogger("publish");
const confirm = args.confirm === true;

const chosenPath = resolve(String(args.chosen ?? ".tmp-photo-candidates/chosen.json"));
const chosen = readJsonIfExists(chosenPath, null);
if (!Array.isArray(chosen) || chosen.length === 0) {
  logger.log(`no entries in ${chosenPath}; nothing to publish`);
  process.exit(0);
}

const sqlEsc = (s) => String(s).replace(/'/g, "''");
const stamp = new Date().toISOString().slice(0, 10);
const sqlPath = join(REPORTS_DIR, `publish-${stamp}.sql`);
mkdirSync(REPORTS_DIR, { recursive: true });
mkdirSync(PREVIEW_DIR, { recursive: true });
if (!existsSync(sqlPath)) {
  writeFileSync(
    sqlPath,
    `-- Generated by scripts/photos/3-publish.mjs on ${new Date().toISOString()}\n` +
      `-- Review each row, then run in the Supabase SQL editor. Every statement is idempotent.\n` +
      `-- hero_image_credit holds the Commons source page; hero_image_attribution is "Author / Licence".\n\n`,
  );
}

if (confirm) {
  const state = await ensurePublicBucket(env, BUCKET, { allowedMime: ["image/jpeg", "image/png", "image/webp"] });
  logger.log(`bucket ${BUCKET}: ${state}`);
} else {
  logger.log(`dry run: JPEGs go to ${PREVIEW_DIR}; pass --confirm to upload`);
}

const credits = readJsonIfExists(CREDITS_JSON, {});
let published = 0;
let refused = 0;
for (const entry of chosen) {
  const manifest = readJsonIfExists(join(OUT_DIR, entry.slug, "manifest.json"), null);
  const cand = manifest?.candidates?.[entry.index];
  if (!manifest || !cand) {
    refused++;
    logger.log(`${entry.slug}: no candidate #${entry.index} in manifest; skipped`);
    continue;
  }
  if (!ALLOWED_LICENCE.test(cand.licence ?? "") || FORBIDDEN_LICENCE.test(cand.licence ?? "")) {
    refused++;
    logger.log(`${entry.slug}: licence "${cand.licence}" is outside the allow-list; skipped`);
    continue;
  }
  const src = resolve(cand.file);
  if (!existsSync(src)) {
    refused++;
    logger.log(`${entry.slug}: ${cand.file} missing on disk; re-run the harvest with --force --slug ${entry.slug}`);
    continue;
  }
  try {
    // 16:9 at 1600 wide from the 1280 thumb means a mild upscale on some
    // files; the hero sits under a scrim so that is acceptable, and the
    // original is kept reachable through sourcePage for a later re-cut.
    const jpeg = await sharp(src)
      .resize(1600, 900, { fit: "cover", position: sharp.strategy.attention, withoutEnlargement: false })
      .jpeg({ quality: 82, mozjpeg: true })
      .toBuffer();
    let url;
    if (confirm) {
      url = await uploadObject(env, BUCKET, `${entry.slug}.jpg`, jpeg, "image/jpeg");
    } else {
      writeFileSync(join(PREVIEW_DIR, `${entry.slug}.jpg`), jpeg);
      url = `${env.supabaseUrl}/storage/v1/object/public/${BUCKET}/${entry.slug}.jpg`;
    }
    const attribution = `${cand.author} / ${cand.licence}`;
    const alt = `${manifest.name} — ${manifest.state} ski resort in winter`;
    appendFileSync(
      sqlPath,
      `-- ${manifest.name} (${manifest.state}) · ${cand.title} · ${entry.reason ?? ""}\n` +
        `UPDATE resorts SET hero_image_url = '${sqlEsc(url)}', hero_image_source = 'supabase', ` +
        `hero_image_attribution = '${sqlEsc(attribution)}', hero_image_credit = '${sqlEsc(cand.sourcePage)}', ` +
        `hero_image_alt = '${sqlEsc(alt)}', hero_image_verified_winter = true, updated_at = now() ` +
        `WHERE slug = '${sqlEsc(entry.slug)}';\n\n`,
    );
    credits[entry.slug] = { title: cand.title, sourcePage: cand.sourcePage, attribution, licenceUrl: cand.licenceUrl ?? null, publishedAt: new Date().toISOString() };
    published++;
    logger.log(`${entry.slug}: ${confirm ? "uploaded" : "previewed"} ${cand.title} (${cand.licence})`);
  } catch (e) {
    refused++;
    logger.log(`${entry.slug}: FAILED ${e.message}`);
  }
}
writeJson(CREDITS_JSON, Object.fromEntries(Object.entries(credits).sort(([a], [b]) => a.localeCompare(b))));
logger.log(`publish: ${published} ${confirm ? "uploaded" : "previewed"}, ${refused} skipped; SQL at ${sqlPath}`);
