// Step 3 of the resort photo pipeline: publish the photos the vetting pass
// chose. It is the step that follows the human + vision vetting described
// in handoff-docs/PHOTOS_2026-09-23.md (first used on 2026-09-23).
//
//   node scripts/photos/3-publish.mjs --chosen .tmp-photo-candidates/chosen.json [--confirm]
//
// Input: chosen.json, one entry per resort:
//   [{ "slug": "alta", "index": 2, "reason": "lift + fresh snow, no faces",
//      "author": "Optional manual credit when the file names nobody" }, ...]
//   `index` is the cand-N number in .tmp-photo-candidates/<slug>/manifest.json.
//
// For each entry it:
//   1. Re-reads the file's licence and author LIVE from Commons (the
//      manifest may be weeks old, and manifests written before 2026-09-23
//      fell back to "Own work" or the uploader account for the author).
//      Refuses anything outside {CC0, public domain, CC BY, CC BY-SA}, and
//      refuses a CC BY / BY-SA file whose author is unknown unless the
//      chosen.json entry supplies "author".
//   2. Crops the 1280 px thumb to 16:9 (attention-based crop), resizes to
//      1600 wide, JPEG q82.
//   3. Dry run (default): writes the JPEG to
//      .tmp-photo-candidates/publish-preview/<slug>.jpg and the would-be
//      rows to .tmp-photo-candidates/publish-preview/plan.json. Nothing
//      else: no SQL, no change to lib/data/heroCredits.json, because a
//      statement pointing at an object that was never uploaded would 404
//      every hero it touched, and /credits would describe photos that are
//      not live.
//   4. With --confirm: uploads to the public bucket resort-heroes under a
//      content-addressed name, <slug>-<sha8>.jpg (1-year cache). A new
//      photo always gets a new URL, so no browser or optimizer cache can
//      keep showing the old image under the new credit. Then appends an
//      UPDATE to scripts/photos/reports/publish-<date>.sql and merges the
//      credit into lib/data/heroCredits.json keyed by that exact URL.
//
// It never runs SQL. The generated file is applied by a human in the
// Supabase SQL editor after a last look; until then the old hero (or the
// terrain card) keeps showing, and heroCredits.json only takes effect for
// a row whose hero_image_url equals the entry's url.

import sharp from "sharp";
import { existsSync, mkdirSync, writeFileSync, appendFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  loadEnv,
  ensurePublicBucket,
  uploadObject,
  readJsonIfExists,
  writeJson,
  parseArgs,
  makeLogger,
  contentHash,
  commonsFileInfo,
  commonsAuthor,
  tidyAuthor,
  stripHtml,
  attributionString,
  sqlComment,
  REPORTS_DIR,
} from "./_shared.mjs";

const OUT_DIR = resolve(".tmp-photo-candidates");
const PREVIEW_DIR = join(OUT_DIR, "publish-preview");
const CREDITS_JSON = resolve("lib/data/heroCredits.json");
const BUCKET = "resort-heroes";
const ALLOWED_LICENCE = /^(CC0|Public domain|PD|CC[ -]BY(-SA)?(\s|$|[ -]\d))/i;
const FORBIDDEN_LICENCE = /\b(NC|ND)\b/i;
// Licences whose terms require naming the author wherever the photo shows.
const NEEDS_AUTHOR = /^CC[ -]BY/i;

const args = parseArgs();
const env = loadEnv();
const logger = makeLogger("publish");
const confirm = args.confirm === true;

const chosenPath = resolve(String(args.chosen ?? ".tmp-photo-candidates/chosen.json"));
const chosen = readJsonIfExists(chosenPath, null);
if (!Array.isArray(chosen) || chosen.length === 0) {
  logger.log(`no entries in ${chosenPath}; nothing to publish`);
  process.exit(0);
}

const sqlEsc = (s) => String(s).replace(/'/g, "''");
const stamp = new Date().toISOString().slice(0, 10);
const sqlPath = join(REPORTS_DIR, `publish-${stamp}.sql`);
mkdirSync(PREVIEW_DIR, { recursive: true });

if (confirm) {
  const state = await ensurePublicBucket(env, BUCKET, { allowedMime: ["image/jpeg", "image/png", "image/webp"] });
  logger.log(`bucket ${BUCKET}: ${state}`);
  mkdirSync(REPORTS_DIR, { recursive: true });
  if (!existsSync(sqlPath)) {
    writeFileSync(
      sqlPath,
      `-- Generated by scripts/photos/3-publish.mjs --confirm on ${new Date().toISOString()}\n` +
        `-- Every object named below was uploaded by that run. Review each row, then run in the\n` +
        `-- Supabase SQL editor. Every statement is idempotent.\n` +
        `-- hero_image_credit holds the Commons source page; hero_image_attribution is "Author / Licence".\n\n`,
    );
  }
} else {
  logger.log(`dry run: JPEGs and plan.json go to ${PREVIEW_DIR}; no SQL and no credits change. Pass --confirm to publish.`);
}

// Live Commons metadata for every chosen file, one request per 20 titles.
const picks = chosen.map((entry) => {
  const manifest = readJsonIfExists(join(OUT_DIR, entry.slug, "manifest.json"), null);
  return { entry, manifest, cand: manifest?.candidates?.[entry.index] ?? null };
});
const live = await commonsFileInfo(picks.filter((p) => p.cand).map((p) => p.cand.title));

const credits = readJsonIfExists(CREDITS_JSON, {});
const plan = [];
let published = 0;
let refused = 0;
for (const { entry, manifest, cand } of picks) {
  if (!manifest || !cand) {
    refused++;
    logger.log(`${entry.slug}: no candidate #${entry.index} in manifest; skipped`);
    continue;
  }
  const info = live.get(cand.title);
  if (!info || info.missing) {
    refused++;
    logger.log(`${entry.slug}: ${cand.title} is gone from Commons (deleted or renamed); skipped`);
    continue;
  }
  const meta = info.extmetadata ?? {};
  const licence = stripHtml(meta.LicenseShortName?.value ?? meta.License?.value);
  if (!ALLOWED_LICENCE.test(licence) || FORBIDDEN_LICENCE.test(licence)) {
    refused++;
    logger.log(`${entry.slug}: licence "${licence}" is outside the allow-list; skipped`);
    continue;
  }
  const author = tidyAuthor(entry.author) ?? commonsAuthor(meta);
  if (!author && NEEDS_AUTHOR.test(licence)) {
    refused++;
    logger.log(`${entry.slug}: ${licence} needs an author and Commons names none; add "author" to the chosen.json entry after checking ${cand.sourcePage}`);
    continue;
  }
  const src = resolve(cand.file);
  if (!existsSync(src)) {
    refused++;
    logger.log(`${entry.slug}: ${cand.file} missing on disk; re-run the harvest with --force --slug ${entry.slug}`);
    continue;
  }
  try {
    // 16:9 at 1600 wide from the 1280 thumb means a mild upscale on some
    // files; the hero sits under a scrim so that is acceptable, and the
    // original is kept reachable through sourcePage for a later re-cut.
    const jpeg = await sharp(src)
      .resize(1600, 900, { fit: "cover", position: sharp.strategy.attention, withoutEnlargement: false })
      .jpeg({ quality: 82, mozjpeg: true })
      .toBuffer();
    const objectName = `${entry.slug}-${contentHash(jpeg)}.jpg`;
    const attribution = attributionString(author, licence);
    const alt = `${manifest.name}, ${manifest.state} ski resort in winter`;
    const licenceUrl = stripHtml(meta.LicenseUrl?.value) || null;
    const sourcePage = info.descriptionurl ?? cand.sourcePage;

    if (!confirm) {
      writeFileSync(join(PREVIEW_DIR, `${entry.slug}.jpg`), jpeg);
      plan.push({ slug: entry.slug, objectName, title: cand.title, attribution, sourcePage, alt, reason: entry.reason ?? null });
      published++;
      logger.log(`${entry.slug}: previewed ${cand.title} (${attribution})`);
      continue;
    }

    const url = await uploadObject(env, BUCKET, objectName, jpeg, "image/jpeg");
    appendFileSync(
      sqlPath,
      `-- ${sqlComment(`${manifest.name} (${manifest.state}) · ${cand.title} · ${entry.reason ?? ""}`)}\n` +
        `UPDATE resorts SET hero_image_url = '${sqlEsc(url)}', hero_image_source = 'supabase', ` +
        `hero_image_attribution = '${sqlEsc(attribution)}', hero_image_credit = '${sqlEsc(sourcePage)}', ` +
        `hero_image_alt = '${sqlEsc(alt)}', hero_image_verified_winter = true, updated_at = now() ` +
        `WHERE slug = '${sqlEsc(entry.slug)}';\n\n`,
    );
    credits[entry.slug] = { title: cand.title, sourcePage, url, author, licence, licenceUrl, attribution, publishedAt: new Date().toISOString() };
    published++;
    logger.log(`${entry.slug}: uploaded ${objectName} from ${cand.title} (${attribution})`);
  } catch (e) {
    refused++;
    logger.log(`${entry.slug}: FAILED ${e.message}`);
  }
}

if (confirm) {
  writeJson(CREDITS_JSON, Object.fromEntries(Object.entries(credits).sort(([a], [b]) => a.localeCompare(b))));
  logger.log(`publish: ${published} uploaded, ${refused} skipped; SQL at ${sqlPath}; commit lib/data/heroCredits.json with it`);
} else {
  writeJson(join(PREVIEW_DIR, "plan.json"), { generatedAt: new Date().toISOString(), note: "Dry run. Nothing was uploaded; do not turn this into SQL.", plan });
  logger.log(`publish dry run: ${published} previewed, ${refused} skipped; plan at ${join(PREVIEW_DIR, "plan.json")}`);
}
