// IATA → airport lookup for the resort page's "Closest airport" card.
//
// Covers every `closest_airport_iata` value in the resorts table (read-only
// query, 2026-09-23: 139 distinct codes on 382 rows) plus the NYC codes
// the map's airport filter offers. The DB stores only the code and, for
// 4 of 425 rows, a distance — so the card showed "✈️ BTV" and nothing
// else (audit resort-panel-detail-17). Coordinates are the published
// airport reference points (rounded to ~0.01°, i.e. within a mile), used
// with lib/distance's haversine + drive model to label an ESTIMATED
// distance; the UI always marks that number as an estimate.

export type Airport = {
  iata: string;
  name: string;
  city: string;
  state: string;
  lat: number;
  lng: number;
};

const AIRPORT_LIST: Airport[] = [
  { iata: "ABE", name: "Lehigh Valley International", city: "Allentown", state: "PA", lat: 40.65, lng: -75.44 },
  { iata: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", state: "NM", lat: 35.04, lng: -106.61 },
  { iata: "ALB", name: "Albany International", city: "Albany", state: "NY", lat: 42.75, lng: -73.8 },
  { iata: "ALS", name: "San Luis Valley Regional", city: "Alamosa", state: "CO", lat: 37.43, lng: -105.87 },
  { iata: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", state: "AK", lat: 61.17, lng: -149.99 },
  { iata: "ART", name: "Watertown International", city: "Watertown", state: "NY", lat: 43.99, lng: -76.02 },
  { iata: "ASE", name: "Aspen/Pitkin County", city: "Aspen", state: "CO", lat: 39.22, lng: -106.87 },
  { iata: "ATW", name: "Appleton International", city: "Appleton", state: "WI", lat: 44.26, lng: -88.52 },
  { iata: "AUG", name: "Augusta State", city: "Augusta", state: "ME", lat: 44.32, lng: -69.8 },
  { iata: "AVL", name: "Asheville Regional", city: "Asheville", state: "NC", lat: 35.44, lng: -82.54 },
  { iata: "AVP", name: "Wilkes-Barre/Scranton International", city: "Scranton", state: "PA", lat: 41.34, lng: -75.72 },
  { iata: "AXN", name: "Alexandria Municipal", city: "Alexandria", state: "MN", lat: 45.87, lng: -95.39 },
  { iata: "AZO", name: "Kalamazoo/Battle Creek International", city: "Kalamazoo", state: "MI", lat: 42.23, lng: -85.55 },
  { iata: "BDL", name: "Bradley International", city: "Hartford", state: "CT", lat: 41.94, lng: -72.68 },
  { iata: "BGR", name: "Bangor International", city: "Bangor", state: "ME", lat: 44.81, lng: -68.83 },
  { iata: "BIL", name: "Billings Logan International", city: "Billings", state: "MT", lat: 45.81, lng: -108.54 },
  { iata: "BIS", name: "Bismarck Airport", city: "Bismarck", state: "ND", lat: 46.77, lng: -100.75 },
  { iata: "BJI", name: "Bemidji Regional", city: "Bemidji", state: "MN", lat: 47.51, lng: -94.93 },
  { iata: "BKE", name: "Baker City Municipal", city: "Baker City", state: "OR", lat: 44.84, lng: -117.81 },
  { iata: "BKW", name: "Raleigh County Memorial", city: "Beckley", state: "WV", lat: 37.79, lng: -81.12 },
  { iata: "BLI", name: "Bellingham International", city: "Bellingham", state: "WA", lat: 48.79, lng: -122.54 },
  { iata: "BOI", name: "Boise Airport", city: "Boise", state: "ID", lat: 43.56, lng: -116.22 },
  { iata: "BOS", name: "Boston Logan International", city: "Boston", state: "MA", lat: 42.37, lng: -71.01 },
  { iata: "BRD", name: "Brainerd Lakes Regional", city: "Brainerd", state: "MN", lat: 46.4, lng: -94.14 },
  { iata: "BTM", name: "Bert Mooney Airport", city: "Butte", state: "MT", lat: 45.95, lng: -112.5 },
  { iata: "BTV", name: "Burlington International", city: "Burlington", state: "VT", lat: 44.47, lng: -73.15 },
  { iata: "BUF", name: "Buffalo Niagara International", city: "Buffalo", state: "NY", lat: 42.94, lng: -78.73 },
  { iata: "BWI", name: "Baltimore/Washington International", city: "Baltimore", state: "MD", lat: 39.18, lng: -76.67 },
  { iata: "BZN", name: "Bozeman Yellowstone International", city: "Bozeman", state: "MT", lat: 45.78, lng: -111.15 },
  { iata: "CDV", name: "Merle K. Smith Airport", city: "Cordova", state: "AK", lat: 60.49, lng: -145.48 },
  { iata: "CHA", name: "Chattanooga Metropolitan", city: "Chattanooga", state: "TN", lat: 35.04, lng: -85.2 },
  { iata: "CHO", name: "Charlottesville-Albemarle", city: "Charlottesville", state: "VA", lat: 38.14, lng: -78.45 },
  { iata: "CKB", name: "North Central West Virginia", city: "Clarksburg", state: "WV", lat: 39.29, lng: -80.23 },
  { iata: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", state: "OH", lat: 41.41, lng: -81.85 },
  { iata: "CLM", name: "William R. Fairchild International", city: "Port Angeles", state: "WA", lat: 48.12, lng: -123.5 },
  { iata: "CLT", name: "Charlotte Douglas International", city: "Charlotte", state: "NC", lat: 35.21, lng: -80.94 },
  { iata: "CMH", name: "John Glenn Columbus International", city: "Columbus", state: "OH", lat: 39.99, lng: -82.89 },
  { iata: "CMX", name: "Houghton County Memorial", city: "Hancock", state: "MI", lat: 47.17, lng: -88.49 },
  { iata: "COD", name: "Yellowstone Regional", city: "Cody", state: "WY", lat: 44.52, lng: -109.02 },
  { iata: "COS", name: "Colorado Springs Airport", city: "Colorado Springs", state: "CO", lat: 38.81, lng: -104.7 },
  { iata: "CPR", name: "Casper-Natrona County International", city: "Casper", state: "WY", lat: 42.91, lng: -106.46 },
  { iata: "CVG", name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", state: "KY", lat: 39.05, lng: -84.67 },
  { iata: "CWA", name: "Central Wisconsin Airport", city: "Mosinee", state: "WI", lat: 44.78, lng: -89.67 },
  { iata: "DBQ", name: "Dubuque Regional", city: "Dubuque", state: "IA", lat: 42.4, lng: -90.71 },
  { iata: "DEN", name: "Denver International", city: "Denver", state: "CO", lat: 39.86, lng: -104.67 },
  { iata: "DLH", name: "Duluth International", city: "Duluth", state: "MN", lat: 46.84, lng: -92.19 },
  { iata: "DRO", name: "Durango-La Plata County", city: "Durango", state: "CO", lat: 37.15, lng: -107.75 },
  { iata: "DSM", name: "Des Moines International", city: "Des Moines", state: "IA", lat: 41.53, lng: -93.66 },
  { iata: "DTW", name: "Detroit Metropolitan", city: "Detroit", state: "MI", lat: 42.21, lng: -83.35 },
  { iata: "EAT", name: "Pangborn Memorial", city: "Wenatchee", state: "WA", lat: 47.4, lng: -120.21 },
  { iata: "EAU", name: "Chippewa Valley Regional", city: "Eau Claire", state: "WI", lat: 44.87, lng: -91.48 },
  { iata: "EGE", name: "Eagle County Regional", city: "Eagle (Vail)", state: "CO", lat: 39.64, lng: -106.92 },
  { iata: "EKO", name: "Elko Regional", city: "Elko", state: "NV", lat: 40.82, lng: -115.79 },
  { iata: "ELP", name: "El Paso International", city: "El Paso", state: "TX", lat: 31.81, lng: -106.38 },
  { iata: "ERI", name: "Erie International", city: "Erie", state: "PA", lat: 42.08, lng: -80.18 },
  { iata: "EUG", name: "Eugene Airport", city: "Eugene", state: "OR", lat: 44.12, lng: -123.21 },
  { iata: "EWR", name: "Newark Liberty International", city: "Newark", state: "NJ", lat: 40.69, lng: -74.17 },
  { iata: "FAI", name: "Fairbanks International", city: "Fairbanks", state: "AK", lat: 64.82, lng: -147.86 },
  { iata: "FAR", name: "Hector International", city: "Fargo", state: "ND", lat: 46.92, lng: -96.82 },
  { iata: "FAT", name: "Fresno Yosemite International", city: "Fresno", state: "CA", lat: 36.78, lng: -119.72 },
  { iata: "FCA", name: "Glacier Park International", city: "Kalispell", state: "MT", lat: 48.31, lng: -114.26 },
  { iata: "FLG", name: "Flagstaff Pulliam", city: "Flagstaff", state: "AZ", lat: 35.14, lng: -111.67 },
  { iata: "FSD", name: "Sioux Falls Regional", city: "Sioux Falls", state: "SD", lat: 43.58, lng: -96.74 },
  { iata: "GEG", name: "Spokane International", city: "Spokane", state: "WA", lat: 47.62, lng: -117.53 },
  { iata: "GFK", name: "Grand Forks International", city: "Grand Forks", state: "ND", lat: 47.95, lng: -97.18 },
  { iata: "GJT", name: "Grand Junction Regional", city: "Grand Junction", state: "CO", lat: 39.12, lng: -108.53 },
  { iata: "GRB", name: "Green Bay Austin Straubel International", city: "Green Bay", state: "WI", lat: 44.49, lng: -88.13 },
  { iata: "GRR", name: "Gerald R. Ford International", city: "Grand Rapids", state: "MI", lat: 42.88, lng: -85.52 },
  { iata: "GTF", name: "Great Falls International", city: "Great Falls", state: "MT", lat: 47.48, lng: -111.37 },
  { iata: "GUC", name: "Gunnison-Crested Butte Regional", city: "Gunnison", state: "CO", lat: 38.53, lng: -106.93 },
  { iata: "GWS", name: "Glenwood Springs Municipal", city: "Glenwood Springs", state: "CO", lat: 39.51, lng: -107.31 },
  { iata: "HDN", name: "Yampa Valley Regional", city: "Hayden (Steamboat)", state: "CO", lat: 40.48, lng: -107.22 },
  { iata: "HGR", name: "Hagerstown Regional", city: "Hagerstown", state: "MD", lat: 39.71, lng: -77.73 },
  { iata: "HLN", name: "Helena Regional", city: "Helena", state: "MT", lat: 46.61, lng: -111.98 },
  { iata: "HPN", name: "Westchester County", city: "White Plains", state: "NY", lat: 41.07, lng: -73.71 },
  { iata: "IDA", name: "Idaho Falls Regional", city: "Idaho Falls", state: "ID", lat: 43.51, lng: -112.07 },
  { iata: "IMT", name: "Ford Airport", city: "Iron Mountain", state: "MI", lat: 45.82, lng: -88.11 },
  { iata: "IPT", name: "Williamsport Regional", city: "Williamsport", state: "PA", lat: 41.24, lng: -76.92 },
  { iata: "IWD", name: "Gogebic-Iron County", city: "Ironwood", state: "MI", lat: 46.53, lng: -90.13 },
  { iata: "JAC", name: "Jackson Hole Airport", city: "Jackson", state: "WY", lat: 43.61, lng: -110.74 },
  { iata: "JFK", name: "John F. Kennedy International", city: "New York", state: "NY", lat: 40.64, lng: -73.78 },
  { iata: "JNU", name: "Juneau International", city: "Juneau", state: "AK", lat: 58.35, lng: -134.58 },
  { iata: "LAR", name: "Laramie Regional", city: "Laramie", state: "WY", lat: 41.31, lng: -105.68 },
  { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", state: "NV", lat: 36.08, lng: -115.15 },
  { iata: "LBE", name: "Arnold Palmer Regional", city: "Latrobe", state: "PA", lat: 40.28, lng: -79.4 },
  { iata: "LEB", name: "Lebanon Municipal", city: "Lebanon", state: "NH", lat: 43.63, lng: -72.3 },
  { iata: "LGA", name: "LaGuardia", city: "New York", state: "NY", lat: 40.78, lng: -73.87 },
  { iata: "LGU", name: "Logan-Cache Airport", city: "Logan", state: "UT", lat: 41.79, lng: -111.85 },
  { iata: "LKV", name: "Lake County Airport", city: "Lakeview", state: "OR", lat: 42.16, lng: -120.4 },
  { iata: "LSE", name: "La Crosse Regional", city: "La Crosse", state: "WI", lat: 43.88, lng: -91.26 },
  { iata: "LWB", name: "Greenbrier Valley", city: "Lewisburg", state: "WV", lat: 37.86, lng: -80.4 },
  { iata: "LWS", name: "Lewiston-Nez Perce County", city: "Lewiston", state: "ID", lat: 46.37, lng: -117.02 },
  { iata: "MBS", name: "MBS International", city: "Saginaw", state: "MI", lat: 43.53, lng: -84.08 },
  { iata: "MCI", name: "Kansas City International", city: "Kansas City", state: "MO", lat: 39.3, lng: -94.71 },
  { iata: "MDT", name: "Harrisburg International", city: "Harrisburg", state: "PA", lat: 40.19, lng: -76.76 },
  { iata: "MGW", name: "Morgantown Municipal", city: "Morgantown", state: "WV", lat: 39.64, lng: -79.92 },
  { iata: "MHT", name: "Manchester-Boston Regional", city: "Manchester", state: "NH", lat: 42.93, lng: -71.44 },
  { iata: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee", state: "WI", lat: 42.95, lng: -87.9 },
  { iata: "MLI", name: "Quad Cities International", city: "Moline", state: "IL", lat: 41.45, lng: -90.51 },
  { iata: "MMH", name: "Mammoth Yosemite", city: "Mammoth Lakes", state: "CA", lat: 37.62, lng: -118.84 },
  { iata: "MSN", name: "Dane County Regional", city: "Madison", state: "WI", lat: 43.14, lng: -89.34 },
  { iata: "MSO", name: "Missoula Montana Airport", city: "Missoula", state: "MT", lat: 46.92, lng: -114.09 },
  { iata: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", state: "MN", lat: 44.88, lng: -93.22 },
  { iata: "MSS", name: "Massena International", city: "Massena", state: "NY", lat: 44.94, lng: -74.85 },
  { iata: "MTJ", name: "Montrose Regional", city: "Montrose", state: "CO", lat: 38.51, lng: -107.89 },
  { iata: "MYL", name: "McCall Municipal", city: "McCall", state: "ID", lat: 44.89, lng: -116.1 },
  { iata: "OAK", name: "Oakland International", city: "Oakland", state: "CA", lat: 37.72, lng: -122.22 },
  { iata: "OMA", name: "Eppley Airfield", city: "Omaha", state: "NE", lat: 41.3, lng: -95.89 },
  { iata: "ONT", name: "Ontario International", city: "Ontario", state: "CA", lat: 34.06, lng: -117.6 },
  { iata: "ORD", name: "Chicago O'Hare International", city: "Chicago", state: "IL", lat: 41.98, lng: -87.9 },
  { iata: "PDT", name: "Eastern Oregon Regional", city: "Pendleton", state: "OR", lat: 45.7, lng: -118.84 },
  { iata: "PDX", name: "Portland International", city: "Portland", state: "OR", lat: 45.59, lng: -122.6 },
  { iata: "PHL", name: "Philadelphia International", city: "Philadelphia", state: "PA", lat: 39.87, lng: -75.24 },
  { iata: "PIH", name: "Pocatello Regional", city: "Pocatello", state: "ID", lat: 42.91, lng: -112.6 },
  { iata: "PIT", name: "Pittsburgh International", city: "Pittsburgh", state: "PA", lat: 40.49, lng: -80.23 },
  { iata: "PLN", name: "Pellston Regional", city: "Pellston", state: "MI", lat: 45.57, lng: -84.8 },
  { iata: "PQI", name: "Presque Isle International", city: "Presque Isle", state: "ME", lat: 46.69, lng: -68.04 },
  { iata: "PSC", name: "Tri-Cities Airport", city: "Pasco", state: "WA", lat: 46.26, lng: -119.12 },
  { iata: "PWM", name: "Portland International Jetport", city: "Portland", state: "ME", lat: 43.65, lng: -70.31 },
  { iata: "RAP", name: "Rapid City Regional", city: "Rapid City", state: "SD", lat: 44.05, lng: -103.06 },
  { iata: "RDD", name: "Redding Regional", city: "Redding", state: "CA", lat: 40.51, lng: -122.29 },
  { iata: "RDM", name: "Roberts Field", city: "Redmond (Bend)", state: "OR", lat: 44.25, lng: -121.15 },
  { iata: "RHI", name: "Rhinelander-Oneida County", city: "Rhinelander", state: "WI", lat: 45.63, lng: -89.47 },
  { iata: "RKD", name: "Knox County Regional", city: "Rockland", state: "ME", lat: 44.06, lng: -69.1 },
  { iata: "RNO", name: "Reno-Tahoe International", city: "Reno", state: "NV", lat: 39.5, lng: -119.77 },
  { iata: "ROA", name: "Roanoke-Blacksburg Regional", city: "Roanoke", state: "VA", lat: 37.33, lng: -79.98 },
  { iata: "ROC", name: "Greater Rochester International", city: "Rochester", state: "NY", lat: 43.12, lng: -77.67 },
  { iata: "SAF", name: "Santa Fe Regional", city: "Santa Fe", state: "NM", lat: 35.62, lng: -106.09 },
  { iata: "SBN", name: "South Bend International", city: "South Bend", state: "IN", lat: 41.71, lng: -86.32 },
  { iata: "SDF", name: "Louisville Muhammad Ali International", city: "Louisville", state: "KY", lat: 38.17, lng: -85.74 },
  { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", state: "WA", lat: 47.45, lng: -122.31 },
  { iata: "SGU", name: "St. George Regional", city: "St. George", state: "UT", lat: 37.04, lng: -113.51 },
  { iata: "SHD", name: "Shenandoah Valley Regional", city: "Staunton", state: "VA", lat: 38.26, lng: -78.9 },
  { iata: "SHR", name: "Sheridan County Airport", city: "Sheridan", state: "WY", lat: 44.77, lng: -106.98 },
  { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", state: "UT", lat: 40.79, lng: -111.98 },
  { iata: "SLK", name: "Adirondack Regional", city: "Saranac Lake", state: "NY", lat: 44.39, lng: -74.21 },
  { iata: "SOW", name: "Show Low Regional", city: "Show Low", state: "AZ", lat: 34.27, lng: -110.01 },
  { iata: "SUN", name: "Friedman Memorial", city: "Hailey (Sun Valley)", state: "ID", lat: 43.5, lng: -114.3 },
  { iata: "SWF", name: "New York Stewart International", city: "Newburgh", state: "NY", lat: 41.5, lng: -74.1 },
  { iata: "SYR", name: "Syracuse Hancock International", city: "Syracuse", state: "NY", lat: 43.11, lng: -76.11 },
  { iata: "TEX", name: "Telluride Regional", city: "Telluride", state: "CO", lat: 37.95, lng: -107.91 },
  { iata: "TRI", name: "Tri-Cities Airport", city: "Blountville", state: "TN", lat: 36.48, lng: -82.41 },
  { iata: "TSM", name: "Taos Regional", city: "Taos", state: "NM", lat: 36.46, lng: -105.67 },
  { iata: "TUS", name: "Tucson International", city: "Tucson", state: "AZ", lat: 32.12, lng: -110.94 },
  { iata: "TVC", name: "Cherry Capital Airport", city: "Traverse City", state: "MI", lat: 44.74, lng: -85.58 },
  { iata: "TWF", name: "Magic Valley Regional", city: "Twin Falls", state: "ID", lat: 42.48, lng: -114.49 },
  { iata: "TYS", name: "McGhee Tyson Airport", city: "Knoxville", state: "TN", lat: 35.81, lng: -83.99 },
  { iata: "UNV", name: "University Park Airport", city: "State College", state: "PA", lat: 40.85, lng: -77.85 },
  { iata: "YKM", name: "Yakima Air Terminal", city: "Yakima", state: "WA", lat: 46.57, lng: -120.54 },
];

const BY_IATA: ReadonlyMap<string, Airport> = new Map(AIRPORT_LIST.map((a) => [a.iata, a]));

/** Look up an airport by IATA code (case-insensitive). Null when unknown,
 *  so the UI can still show the bare code rather than nothing. */
export function airportByIata(iata: string | null | undefined): Airport | null {
  if (!iata) return null;
  return BY_IATA.get(iata.trim().toUpperCase()) ?? null;
}

/** Every airport we know, sorted by code — for tests + tooling. */
export function allAirports(): Airport[] {
  return [...AIRPORT_LIST].sort((a, b) => a.iata.localeCompare(b.iata));
}
