// Tier-aware pass access: which products of each pass family work at a
// resort, for how many days, with which blackout dates, and whether a lift
// reservation is needed. Data is lib/data/passAccess.json, generated by
// scripts/build-pass-access.mjs from the verified handoff dataset (see
// handoff-docs/PASS_DATA_2026-09-23.md). resorts.passes[] in the DB stays
// the source of truth for WHICH families a resort is on and for pin
// colours; this module only adds the per-product detail behind each chip.
//
// Honesty rules baked in here:
//   * isBlackedOut returns null (not false) whenever the answer is not
//     known: unpublished lists (Indy 2026-27), option-dependent products
//     (Epic Day Pass with or without peak dates) and products that give no
//     access at all.
//   * Every string we print carries the verified date, and the raw source
//     text is kept next to the parsed ranges so a reader can check us.

import raw from "./data/passAccess.json";

export type PassFamily = "epic" | "ikon" | "indy" | "mountain_collective";

export const PASS_FAMILIES: ReadonlyArray<PassFamily> = [
  "mountain_collective",
  "ikon",
  "epic",
  "indy",
];

export type DaysKind =
  | "unlimited"
  | "limited"
  | "range"
  | "none"
  | "discount"
  | "weekdays"
  | "other";

export type BlackoutStatus =
  /** No blackout dates on this product at this resort. */
  | "none"
  /** Explicit dates (and possibly weekdays) parsed into `ranges`. */
  | "dates"
  /** Only weekdays are restricted (e.g. a midweek pass). */
  | "weekdays"
  /** Depends on the option bought (Epic Day Pass with or without peak dates). */
  | "conditional"
  /** The operator has not published this season's list yet. */
  | "unpublished"
  /** Text we could not parse; `text` is all we have. */
  | "unknown"
  /** The product gives no lift access here, so blackouts do not apply. */
  | "not_applicable";

/** Inclusive ISO date pair, e.g. ["2026-12-26", "2026-12-30"]. */
export type DateRange = [string, string];

export interface Days {
  /** Raw text from the verified dataset. */
  text: string;
  kind: DaysKind;
  /** Short label for chips: "unlimited", "7 days", "2-4 days", "not included". */
  short: string;
  count?: number;
  min?: number;
  max?: number;
  qualifier?: string | null;
}

export interface Blackouts {
  status: BlackoutStatus;
  /** Raw text from the verified dataset, always kept. */
  text: string;
  ranges: DateRange[];
  /** 0 = Sunday … 6 = Saturday; days of the week that are always blacked out. */
  weekdays: number[];
  /** "explicit" when the dates were in the row; "epic-peak-list" when the
   *  row said only "peak dates" and the published Epic list was substituted. */
  rangesSource: "explicit" | "epic-peak-list" | null;
  /** For unpublished lists: what last season's list covered, in plain words. */
  lastSeason: string | null;
  /** "full" = the pass does not work at all on those days; "day-access" =
   *  only 9am-3pm access is removed (Stevens Pass Select) and `note` says
   *  what stays open. A date filter must label the second kind, not hide it. */
  scope: "full" | "day-access";
  /** Sentence that qualifies the ranges (night skiing exception), with ISO
   *  dates the formatter rewrites. */
  note: string | null;
}

export interface PassProductAccess {
  product: string;
  productKey: string;
  /** Tier or age qualifier split from the product name ("All Resorts tier only"). */
  qualifier: string | null;
  days: Days;
  blackouts: Blackouts;
  reservationRequired: boolean;
  /** Ikon Bonus Mountain: 2 days on the full Ikon Pass only, blackouts apply. */
  isBonusMountain: boolean;
  /** Set when the day allotment is shared across several resorts rows. */
  sharedWith: string | null;
  newFor2026_27: boolean;
  sourceUrls: string[];
  verifiedOn: string;
}

export interface FamilyInfo {
  officialUrl: string;
  note: string;
}

export type ResortAccess = Partial<Record<PassFamily, PassProductAccess[]>>;

export interface PassAccessData {
  season: string;
  verifiedOn: string;
  generatedBy: string;
  families: Record<PassFamily, FamilyInfo>;
  resorts: Record<string, ResortAccess>;
}

const data = raw as unknown as PassAccessData;

export const PASS_ACCESS_SEASON = data.season;
export const PASS_ACCESS_VERIFIED_ON = data.verifiedOn;

export function isPassFamily(value: string): value is PassFamily {
  return (PASS_FAMILIES as ReadonlyArray<string>).includes(value);
}

/** Every family's products at a resort, or null when the dataset has no
 *  row for the slug (the resort is independent, or was added after the
 *  last regeneration). */
export function getAccess(slug: string): ResortAccess | null {
  return data.resorts[slug] ?? null;
}

/** Products of one family at a resort, in display order. Empty when the
 *  family is not verified for that slug. */
export function getFamilyAccess(slug: string, family: PassFamily): PassProductAccess[] {
  return data.resorts[slug]?.[family] ?? [];
}

export function familyInfo(family: PassFamily): FamilyInfo {
  return data.families[family];
}

/** Distinct products of a family across the dataset, in display order.
 *  Regional Epic products only appear if some resort lists them. */
export function productsFor(family: PassFamily): Array<{ product: string; productKey: string }> {
  const seen = new Map<string, string>();
  for (const access of Object.values(data.resorts)) {
    for (const entry of access[family] ?? []) {
      if (!seen.has(entry.productKey)) seen.set(entry.productKey, entry.product);
    }
  }
  const order = PRODUCT_ORDER[family];
  return [...seen]
    .map(([productKey, product]) => ({ productKey, product }))
    .sort((a, b) => rank(order, a.productKey) - rank(order, b.productKey) || a.product.localeCompare(b.product));
}

const PRODUCT_ORDER: Record<PassFamily, string[]> = {
  epic: ["epic-pass", "epic-local-pass", "epic-day-pass", "epic-military-pass"],
  ikon: ["ikon-pass", "ikon-base-pass", "ikon-session-pass"],
  indy: ["indy-base-pass", "indy-plus-pass", "indy-base-add-on-pass", "indy-plus-add-on-pass"],
  mountain_collective: ["mountain-collective-pass"],
};

function rank(order: string[], key: string): number {
  const i = order.indexOf(key);
  return i === -1 ? order.length : i;
}

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

function isValidIso(dateISO: string): boolean {
  if (!ISO_DATE.test(dateISO)) return false;
  const d = new Date(dateISO + "T00:00:00Z");
  return !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === dateISO;
}

/** Is `dateISO` a blackout day for `product` (name or key) at `slug`?
 *  true / false when the published rules answer it; null when they do not
 *  (unknown product, unpublished list, option-dependent product, no
 *  access, or an invalid date). Callers must render null as "not announced
 *  yet" or "check the pass", never as "open". A true on a row whose
 *  `blackouts.scope` is "day-access" means no 9am-3pm access; read `note`
 *  before calling the whole day closed. */
export function isBlackedOut(slug: string, product: string, dateISO: string): boolean | null {
  const entry = findProduct(slug, product);
  if (!entry || !isValidIso(dateISO)) return null;
  return isBlackedOutFor(entry, dateISO);
}

/** Same answer as isBlackedOut for an entry already in hand. */
export function isBlackedOutFor(entry: PassProductAccess, dateISO: string): boolean | null {
  if (!isValidIso(dateISO)) return null;
  const b = entry.blackouts;
  switch (b.status) {
    case "none":
      return false;
    case "dates":
    case "weekdays": {
      if (b.ranges.some(([start, end]) => dateISO >= start && dateISO <= end)) return true;
      if (b.weekdays.length) {
        const dow = new Date(dateISO + "T00:00:00Z").getUTCDay();
        if (b.weekdays.includes(dow)) return true;
      }
      return false;
    }
    default:
      return null;
  }
}

function findProduct(slug: string, product: string): PassProductAccess | null {
  const access = data.resorts[slug];
  if (!access) return null;
  const wanted = product.trim().toLowerCase();
  for (const list of Object.values(access)) {
    for (const entry of list) {
      if (entry.productKey === wanted || entry.product.toLowerCase() === wanted) return entry;
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Formatting
// ---------------------------------------------------------------------------

const MONTH_SHORT = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function parts(iso: string): { y: number; m: number; d: number } {
  return { y: +iso.slice(0, 4), m: +iso.slice(5, 7) - 1, d: +iso.slice(8, 10) };
}

/** One range as people write it: "Dec 26-30", "Jan 16", "Dec 20-Jan 4".
 *  With `withYear`, the year (or both years across New Year) is appended. */
export function formatRange([start, end]: DateRange, withYear = false): string {
  const a = parts(start);
  const b = parts(end);
  const yearA = withYear ? `, ${a.y}` : "";
  const yearB = withYear ? `, ${b.y}` : "";
  if (start === end) return `${MONTH_SHORT[a.m]} ${a.d}${yearA}`;
  if (a.m === b.m && a.y === b.y) return `${MONTH_SHORT[a.m]} ${a.d}-${b.d}${yearA}`;
  if (a.y === b.y) return `${MONTH_SHORT[a.m]} ${a.d}-${MONTH_SHORT[b.m]} ${b.d}${yearA}`;
  return `${MONTH_SHORT[a.m]} ${a.d}${yearA}-${MONTH_SHORT[b.m]} ${b.d}${yearB}`;
}

export function formatRanges(ranges: DateRange[], withYear = false, separator = ", "): string {
  return ranges.map((r) => formatRange(r, withYear)).join(separator);
}

const WEEKDAY_NAMES = ["Sundays", "Mondays", "Tuesdays", "Wednesdays", "Thursdays", "Fridays", "Saturdays"];

function weekdayPhrase(weekdays: number[]): string {
  const sorted = [...weekdays].sort((x, y) => x - y);
  if (sorted.length === 2 && sorted[0] === 0 && sorted[1] === 6) return "weekends";
  return sorted.map((d) => WEEKDAY_NAMES[d]).join(" and ");
}

/** Days as a full phrase for the resort page: "Unlimited", "7 days",
 *  "2 days · full Ikon Pass only", "Not included". */
export function daysText(days: Days): string {
  const head = days.short.charAt(0).toUpperCase() + days.short.slice(1);
  return days.qualifier ? `${head} · ${days.qualifier}` : head;
}

/** Blackouts as a full sentence for the resort page. Never invents a date:
 *  an unpublished list says so, and an unparsed text is printed verbatim. */
export function blackoutText(b: Blackouts, withYear = true): string {
  switch (b.status) {
    case "none":
      return "No blackout dates";
    case "not_applicable":
      return "";
    case "dates": {
      const head =
        b.scope === "day-access"
          ? "No daytime (9am-3pm) access on"
          : b.rangesSource === "epic-peak-list"
            ? "Epic peak dates"
            : "Blackout dates";
      const dates = formatRanges(b.ranges, withYear, "; ");
      const wk = b.weekdays.length ? ` and all ${weekdayPhrase(b.weekdays)}` : "";
      const note = b.note ? `. ${formatNote(b.note, withYear)}` : "";
      return `${head}: ${dates}${wk}${note}`;
    }
    case "weekdays":
      return `Not valid on ${weekdayPhrase(b.weekdays)}`;
    case "conditional":
      return `Peak dates blacked out only if you buy the no-peak version: ${formatRanges(b.ranges, withYear, "; ")}`;
    case "unpublished":
      return b.lastSeason
        ? `${PASS_ACCESS_SEASON} blackout dates not announced yet · last season: ${b.lastSeason}`
        : `${PASS_ACCESS_SEASON} blackout dates not announced yet`;
    case "unknown":
      return `Blackout dates: ${b.text}`;
  }
}

/** The generator writes ISO dates into `note` so it stays locale-free;
 *  print them the way the ranges are printed. */
function formatNote(note: string, withYear: boolean): string {
  return note.replace(/(\d{4}-\d{2}-\d{2})(?: to (\d{4}-\d{2}-\d{2}))?/g, (_m, a: string, b?: string) =>
    formatRange([a, b ?? a], withYear),
  );
}

/** Short product labels for chips and the one-line summary. */
export const PRODUCT_SHORT: Record<string, string> = {
  "ikon-pass": "Ikon",
  "ikon-base-pass": "Ikon Base",
  "ikon-session-pass": "Session",
  "epic-pass": "Epic",
  "epic-local-pass": "Epic Local",
  "epic-day-pass": "Epic Day",
  "epic-military-pass": "Military",
  "northeast-value-pass": "NE Value",
  "northeast-midweek-pass": "NE Midweek",
  "tahoe-local-pass": "Tahoe Local",
  "tahoe-value-pass": "Tahoe Value",
  "summit-value-pass": "Summit Value",
  "keystone-plus-pass": "Keystone Plus",
  "keystone-crested-butte-4-pack": "KCB 4-Pack",
  "indy-base-pass": "Indy Base",
  "indy-plus-pass": "Indy+",
  "indy-base-add-on-pass": "Base Add-On",
  "indy-plus-add-on-pass": "Indy+ Add-On",
  "mountain-collective-pass": "MC",
};

export function productShort(entry: Pick<PassProductAccess, "product" | "productKey">): string {
  return PRODUCT_SHORT[entry.productKey] ?? entry.product.replace(/ Pass$/, "");
}

/** How many products the chip summary spells out before "+N more". */
const SUMMARY_MAX = 3;

/** One line per family for the map panel chip, e.g.
 *  "Ikon: unlimited · Ikon Base: 5 days, blackouts Dec 26-30, Jan 16-17, Feb 13-14".
 *  Products that give no access are folded into one "not included" tail.
 *  Null when the family is not verified at this resort. */
export function summaryLine(slug: string, family: PassFamily): string | null {
  const list = getFamilyAccess(slug, family);
  if (!list.length) return null;
  const included = list.filter((e) => e.days.kind !== "none");
  const excluded = list.filter((e) => e.days.kind === "none");
  const bits = included.slice(0, SUMMARY_MAX).map(summaryBit);
  const more = included.length - SUMMARY_MAX;
  if (more > 0) bits.push(`+${more} more`);
  if (excluded.length) {
    bits.push(`${excluded.map(productShort).join(" & ")}: not included`);
  }
  return bits.join(" · ");
}

function summaryBit(e: PassProductAccess): string {
  let s = `${productShort(e)}: ${e.days.short}`;
  if (e.isBonusMountain && e.days.kind === "limited") s += " (full pass only)";
  else if (e.days.kind === "limited" && e.days.qualifier?.startsWith("shared")) s += " (shared)";
  const b = e.blackouts;
  switch (b.status) {
    case "dates": {
      s +=
        b.scope === "day-access"
          ? `, no 9am-3pm access ${formatRanges(b.ranges)}`
          : `, blackouts ${formatRanges(b.ranges)}`;
      if (b.weekdays.length) s += ` + ${weekdayPhrase(b.weekdays)}`;
      if (b.note) s += ` (${formatNote(b.note, false).replace(/^Night/, "night")})`;
      break;
    }
    case "weekdays":
      if (e.days.kind !== "weekdays") s += `, no ${weekdayPhrase(b.weekdays)}`;
      break;
    case "conditional":
      s += ", peak dates optional";
      break;
    case "unpublished":
      s += ", blackouts TBA";
      break;
    case "unknown":
      s += ", blackouts apply";
      break;
    default:
      break;
  }
  if (e.reservationRequired) s += " (reservation required)";
  return s;
}

/** "23 Sep 2026" for the verified stamp. */
export function formatVerifiedOn(iso: string): string {
  if (!isValidIso(iso)) return iso;
  const { y, m, d } = parts(iso);
  return `${d} ${MONTH_SHORT[m]} ${y}`;
}

/** "ikonpass.com" style label for a source link. */
export function sourceHost(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}
