-- Legacy hero re-check, generated by scripts/photos/4-legacy-recheck.mjs on 2026-09-23T18:12:27.670Z.
-- Evidence: scripts/photos/legacy/legacy-recheck.json. Review, then run in the Supabase SQL editor.
-- Every statement is guarded by the hero_image_url it was written for, so it does nothing to a row
-- whose photo has been replaced since. Idempotent.

-- 1. Rejected heroes (lib/data/heroDenylist.json): a different resort, or a licence outside the
--    allow-list. lib/heroSource.ts already skips them (it reads the denylist), so the terrain card
--    shows once the app is deployed; this makes the database agree for every other reader.
--    The URL is kept for the audit trail.
-- 49 Degrees North Mountain Resort (WA) · File:Sugar_Mountain_summit.jpg · File:Sugar_Mountain_summit.jpg is Sugar Mountain, North Carolina (camera 3,199 km from the resort)
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = '49-degrees-north' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/49-degrees-north.jpg';
-- Blue Mountain Resort (PA) · File:Blue_Mountain_Resort.JPG · File:Blue_Mountain_Resort.JPG is Blue Mountain, Ontario (categories: Cableways in Ontario)
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'blue-mountain-resort' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/blue-mountain-resort.jpg';
-- Great Divide (MT) · File:The_Great_Divide.jpg · File:The_Great_Divide.jpg is the Continental Divide chair at Sunshine Village, Banff, Alberta
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'great-divide' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/great-divide.jpg';
-- The Homestead (MI) · File:Homestead-8.jpg · File:Homestead-8.jpg is the Omni Homestead, Hot Springs, Virginia (camera 925 km from the Michigan resort)
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'homestead-resort' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/homestead-resort.jpg';
-- Labrador Mountain (NY) · File:Marble_Mountain_Ski_resort.jpg · File:Marble_Mountain_Ski_resort.jpg is Marble Mountain, Newfoundland and Labrador
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'labrador-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/labrador-mountain.jpg';
-- Mt. Baldy Ski Resort (CA) · File:On_a_high_slope_at_Mt._Baldy_Ski_Resort_in_British_Columbia,_Canada,_raw_and_ragged_mountain_stone_is_exposed_by_a_robust_wind.jpg · The file is Mt. Baldy Ski Resort i
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'mt-baldy' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mt-baldy.jpg';
-- Silver Mountain (ID) · File:Aspen_Mountain_ski_area_aspen_trees_FIS_chair.jpg · File:Aspen_Mountain_ski_area_aspen_trees_FIS_chair.jpg is Aspen Mountain, Colorado (camera 1,187 km from the resort)
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'silver-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/silver-mountain.jpg';
-- Big Boulder (PA) · File:Skier_at_Big_White.jpg · File:Skier_at_Big_White.jpg is Big White Ski Resort, British Columbia
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'big-boulder' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/big-boulder.jpg';
-- Appalachian Ski Mountain (NC) · File:The_Appalachian.jpg · File:The_Appalachian.jpg is the Appalachian hotel at Mountain Creek, Vernon, New Jersey
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'appalachian-ski-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/appalachian-ski-mountain.jpg';
-- Keystone Resort (CO) · File:Breckenridge_Ski_Resort.JPG · File:Breckenridge_Ski_Resort.JPG is Breckenridge seen from Arapahoe Basin; Keystone is only a strip of foreground
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'keystone' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/keystone.jpg';
-- Mt Eyak (AK) · File:Mt_Eyak.jpg · File:Mt_Eyak.jpg is licensed under the Commons attribution-only template (Attribution), which is outside the allow-list (CC0, public domain, CC BY, CC BY-SA); restore
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'mt-eyak' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mt-eyak.jpg';
-- Timber Ridge Ski Area (MI) · File:Timber_ridge.jpg · File:Timber_ridge.jpg was copied from onthesnow.com with an unknown author under FAL; licence outside the allow-list and provenance doubtful
UPDATE resorts SET hero_image_verified_winter = false, updated_at = now() WHERE slug = 'timber-ridge' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/timber-ridge.jpg';

-- 2. Cleaned attribution (live Commons author + licence) and the source page for the rest.
-- Pleasant Mountain: was "Stevage / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Stevage / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Shawnee_Peak_Stevage.jpg', updated_at = now() WHERE slug = 'shawnee-peak' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/shawnee-peak.jpg';
-- Palisades Tahoe: was "Rennett Stowe from USA / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'Rennett Stowe from USA / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Squaw_Valley_Ski_Resort_(3142951947).jpg', updated_at = now() WHERE slug = 'palisades-tahoe' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/palisades-tahoe.jpg';
-- Powderhouse Hill: was "Powderhouse Hill / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Bubblecuffer at English Wikipedia / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Powderhousehilll.jpg', updated_at = now() WHERE slug = 'powderhouse-hill' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/powderhouse-hill.jpg';
-- Ragged Mountain: was "CC BY 3.0"
UPDATE resorts SET hero_image_attribution = 'Jrclark at English Wikipedia / CC BY 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Summit6pack-2002-0330c.jpg', updated_at = now() WHERE slug = 'ragged-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/ragged-mountain.jpg';
-- Alta Ski Area: was "Baileypalblue / Public domain"
UPDATE resorts SET hero_image_attribution = 'Baileypalblue / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Alta_Little_Cottonwood_Canyon.JPG', updated_at = now() WHERE slug = 'alta' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/alta.jpg';
-- Anthony Lakes Mountain Resort: was "Snowsnapper / Public domain"
UPDATE resorts SET hero_image_attribution = 'Snowsnapper / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:AnthonyLakes.JPG', updated_at = now() WHERE slug = 'anthony-lakes' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/anthony-lakes.jpg';
-- Aspen Highlands: was "This Photo was taken by Wolfgang Moroder. Feel free to use my photos, but ple / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Wolfgang Moroder / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Aspen_Highlands_spring_skiing.jpg', updated_at = now() WHERE slug = 'aspen-highlands' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/aspen-highlands.jpg';
-- Bear Valley Mountain Resort: was "Unknown authorUnknown author or not provided / Public domain"
UPDATE resorts SET hero_image_attribution = 'Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Ebbetts_Pass_Scenic_Byway_-_Downhill_Skiing_-_NARA_-_7718122.jpg', updated_at = now() WHERE slug = 'bear-valley-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/bear-valley-mountain.jpg';
-- Beaver Creek Resort: was "Joe Lin / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'Joe Lin / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Mount_Powell_from_Beaver_Creek_Ski_Resort.jpg', updated_at = now() WHERE slug = 'beaver-creek' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/beaver-creek.jpg';
-- Big Powderhorn Mountain: was "Jhansonxi / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Jhansonxi / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Big_Powderhorn_Mountain_-_view_from_Dynamite_Trail.jpg', updated_at = now() WHERE slug = 'big-powderhorn-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/big-powderhorn-mountain.jpg';
-- Big Sky Resort: was "A-Reck / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'A-Reck / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:On_the_Lift_at_Big_Sky_Resort_-_panoramio.jpg', updated_at = now() WHERE slug = 'big-sky' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/big-sky.jpg';
-- Blacktail Mountain Ski Area: was "Katie Brady / CC BY-SA 2.0"
UPDATE resorts SET hero_image_attribution = 'Katie Brady / CC BY-SA 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Blacktail_Mountain.jpg', updated_at = now() WHERE slug = 'blacktail' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/blacktail.jpg';
-- Bogus Basin: was "cifraser1 / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'cifraser1 / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Bogus_Basin_ski_area_(2017).jpg', updated_at = now() WHERE slug = 'bogus-basin' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/bogus-basin.jpg';
-- Bolton Valley: was "Gopats92 / Public domain"
UPDATE resorts SET hero_image_attribution = 'Gopats92 / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:BoltonValleyLodge.jpg', updated_at = now() WHERE slug = 'bolton-valley' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/bolton-valley.jpg';
-- Boreal Mountain Resort: was "Brocken Inaglory / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Brocken Inaglory / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Ski_lodge_in_Boreal.jpg', updated_at = now() WHERE slug = 'boreal-mountain-resort' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/boreal-mountain-resort.jpg';
-- Bousquet Mountain: was "P. S. F. Freitas / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'P. S. F. Freitas / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Bousquet_Ski_Area.jpg', updated_at = now() WHERE slug = 'bousquet-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/bousquet-mountain.jpg';
-- Breckenridge Ski Resort: was "Jasen Miller from Colorado Springs, USA / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'Jasen Miller from Colorado Springs, USA / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Breckenridge_Ski_Resort_from_town.jpg', updated_at = now() WHERE slug = 'breckenridge' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/breckenridge.jpg';
-- Bretton Woods: was "Storylanding / CC0"
UPDATE resorts SET hero_image_attribution = 'Storylanding / CC0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Bretton_Woods_Resort.jpg', updated_at = now() WHERE slug = 'bretton-woods' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/bretton-woods.jpg';
-- Bridger Bowl Ski Area: was "Richard Barley / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'Richard Barley / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Bridger_Bowl.jpg', updated_at = now() WHERE slug = 'bridger-bowl' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/bridger-bowl.jpg';
-- Brighton Resort: was "CC BY-SA 2.5"
UPDATE resorts SET hero_image_attribution = 'Darkbowmen / CC BY-SA 2.5', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Usa_Utah_Brighton_Peaks.jpg', updated_at = now() WHERE slug = 'brighton' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/brighton.jpg';
-- Bristol Mountain: was "meg colombo from Finger Lakes, NY, USA / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'meg colombo from Finger Lakes, NY, USA / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Aerial_view_of_Bristol_Mountain_Ski_Resort_trails.jpg', updated_at = now() WHERE slug = 'bristol-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/bristol-mountain.jpg';
-- Bromley Mountain: was "Jared C. Benedict / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Jared C. Benedict / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Bromley_Mountain_aerial.jpg', updated_at = now() WHERE slug = 'bromley-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/bromley-mountain.jpg';
-- Camelback Mountain Resort: was "Almondpiano / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Almondpiano / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Camelback_Resort_in_Winter.jpg', updated_at = now() WHERE slug = 'camelback-mountain-resort' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/camelback-mountain-resort.jpg';
-- Cannon Mountain: was "Ericshawwhite / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Ericshawwhite / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Mt._Layfayette_from_Cannon_Mountain_Ski.JPG', updated_at = now() WHERE slug = 'cannon-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/cannon-mountain.jpg';
-- Cataloochee Ski Area: was "Tamparitus / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Tamparitus / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Catchaira.jpg', updated_at = now() WHERE slug = 'cataloochee-ski-area' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/cataloochee-ski-area.jpg';
-- Cooper Spur Ski Area: was "Snowsnapper / Public domain"
UPDATE resorts SET hero_image_attribution = 'Snowsnapper / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:CooperSpur.JPG', updated_at = now() WHERE slug = 'cooper-spur-area' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/cooper-spur-area.jpg';
-- Copper Mountain: was "SparkFunElectronics / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'SparkFunElectronics / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Copper_Mountain_-_4419380965.jpg', updated_at = now() WHERE slug = 'copper-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/copper-mountain.jpg';
-- Crested Butte Mountain Resort: was "Peter from Wellesley / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'Peter from Wellesley / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Silver_Queen_Chair,_CBMR.jpg', updated_at = now() WHERE slug = 'crested-butte' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/crested-butte.jpg';
-- Crotched Mountain: was "Pretzel4 / CC0"
UPDATE resorts SET hero_image_attribution = 'Pretzel4 / CC0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Crotched_Mountain_NH.jpg', updated_at = now() WHERE slug = 'crotched-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/crotched-mountain.jpg';
-- Crystal Mountain: was "ZhengZhou / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'ZhengZhou / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Crystal_Mountain_WA.JPG', updated_at = now() WHERE slug = 'crystal-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/crystal-mountain.jpg';
-- Crystal Mountain (MI): was "Jhansonxi / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Jhansonxi / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Crystal_Mountain_-_Cheers_Chair.jpg', updated_at = now() WHERE slug = 'crystal-mountain-mi' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/crystal-mountain-mi.jpg';
-- Eaglecrest Ski Area: was "Jsayre64 / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Jsayre64 / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Eaglecrest_Ski_Area,_untracked_snow.jpg', updated_at = now() WHERE slug = 'eaglecrest-ski-area' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/eaglecrest-ski-area.jpg';
-- Gore Mountain: was "Ian Taylor Iant333 / Public domain"
UPDATE resorts SET hero_image_attribution = 'Ian Taylor Iant333 / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Ski_003.jpg', updated_at = now() WHERE slug = 'gore-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/gore-mountain.jpg';
-- Grand Targhee Resort: was "Richardmouser / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Richardmouser / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Grand_Targhee_Ski_Resort,_February_2021.jpg', updated_at = now() WHERE slug = 'grand-targhee' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/grand-targhee.jpg';
-- Granite Peak Ski Area: was "Connie Ma from United States of America / CC BY-SA 2.0"
UPDATE resorts SET hero_image_attribution = 'Connie Ma from United States of America / CC BY-SA 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Granite_Peak_Ski_Area.jpg', updated_at = now() WHERE slug = 'granite-peak' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/granite-peak.jpg';
-- Greek Peak: was "Douglas Camin / CC0"
UPDATE resorts SET hero_image_attribution = 'Douglas Camin / CC0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Greek_Peak_Ski_Resort_2026.jpg', updated_at = now() WHERE slug = 'greek-peak' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/greek-peak.jpg';
-- Heavenly Mountain Resort: was "JMatazzoni (WMF) / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'JMatazzoni (WMF) / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Welcome_to_California_sign,_Heavenly_resort,_Lake_Tahoe.jpg', updated_at = now() WHERE slug = 'heavenly-mountain-resort' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/heavenly-mountain-resort.jpg';
-- Holiday Mountain: was "EgorovaSvetlana / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'EgorovaSvetlana / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Holiday_Mountain_Ski_Monticello_Catskills.jpg', updated_at = now() WHERE slug = 'holiday-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/holiday-mountain.jpg';
-- Homewood Mountain Resort: was "User:JGonera (WMF) / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'User:JGonera (WMF) / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Lake_Tahoe_in_winter_seen_from_Homewood,_California.jpg', updated_at = now() WHERE slug = 'homewood-mountain-resort' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/homewood-mountain-resort.jpg';
-- Hoodoo: was "SkiHoodoo / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'SkiHoodoo / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Hoodoo-Ski-Area-Central-Oregon-Resort-Lodge.JPG', updated_at = now() WHERE slug = 'hoodoo' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/hoodoo.jpg';
-- Howelsen Hill Ski Area: was "sherrymain from USA / CC BY-SA 2.0"
UPDATE resorts SET hero_image_attribution = 'sherrymain from USA / CC BY-SA 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Howelsen_Hill_01.jpg', updated_at = now() WHERE slug = 'howelsen-hill' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/howelsen-hill.jpg';
-- Hunter Mountain: was "Ryssby at English Wikipedia (Robert Swanson) / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Ryssby at the English-language Wikipedia / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Hunter_Mountain_ski_area.jpg', updated_at = now() WHERE slug = 'hunter-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/hunter-mountain.jpg';
-- Indianhead Mountain: was "Rickdrew at English Wikipedia / CC BY 3.0"
UPDATE resorts SET hero_image_attribution = 'Rickdrew at English Wikipedia / CC BY 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Indianhead-skilift-1.JPG', updated_at = now() WHERE slug = 'indianhead-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/indianhead-mountain.jpg';
-- Jackson Hole Mountain Resort: was "Wikimedia Commons"
UPDATE resorts SET hero_image_attribution = 'Enricokamasa / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Corbet%27s_Couloir_jackson_hole.jpg', updated_at = now() WHERE slug = 'jackson-hole' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/jackson-hole.jpg';
-- Jay Peak: was "Hanumanix at English Wikipedia / Public domain"
UPDATE resorts SET hero_image_attribution = 'Hanumanix at English Wikipedia / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Jay_Peak.JPG', updated_at = now() WHERE slug = 'jay-peak' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/jay-peak.jpg';
-- June Mountain: was "Eric T Gunther / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Eric T Gunther / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:June_Mountain_skiing.jpg', updated_at = now() WHERE slug = 'june-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/june-mountain.jpg';
-- Killington: was "Wikimedia Commons"
UPDATE resorts SET hero_image_attribution = 'EgorovaSvetlana / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Express_gondola_K-1_Killington_Ski_Area.jpg', updated_at = now() WHERE slug = 'killington' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/killington.jpg';
-- Kirkwood Mountain Resort: was "skeight976 / CC BY 3.0"
UPDATE resorts SET hero_image_attribution = 'skeight976 / CC BY 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Great_Pow_Line_near_Kirkwood_Hwy_88_california_-_panoramio.jpg', updated_at = now() WHERE slug = 'kirkwood-mountain-resort' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/kirkwood-mountain-resort.jpg';
-- Liberty Mountain: was "Baileypalblue / Public domain"
UPDATE resorts SET hero_image_attribution = 'Baileypalblue / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Liberty_Mountain_Resort_front.JPG', updated_at = now() WHERE slug = 'liberty-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/liberty-mountain.jpg';
-- Lutsen Mountains: was "Wikimedia Commons"
UPDATE resorts SET hero_image_attribution = 'Tony Webster from Minneapolis, Minnesota, United States / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Lutsen_Mountains_Ski_Hill,_Minnesota_in_Winter_(46676752794).jpg', updated_at = now() WHERE slug = 'lutsen-mountains' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/lutsen-mountains.jpg';
-- Mad River Glen: was "Jrclark (talk) / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Jrclark at English Wikipedia / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Mad_River_Glen,_single_chair-2005-0118a.jpg', updated_at = now() WHERE slug = 'mad-river-glen' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mad-river-glen.jpg';
-- Magic Mountain: was "Jared C. Benedict / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Jared C. Benedict / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Magic_Mountain_aerial.jpg', updated_at = now() WHERE slug = 'magic-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/magic-mountain.jpg';
-- Mammoth Mountain Ski Area: was "Karissa Kunihira / CC BY 3.0"
UPDATE resorts SET hero_image_attribution = 'Karissa Kunihira / CC BY 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Mammoth_Mountain_Eagle_Express.JPG', updated_at = now() WHERE slug = 'mammoth-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mammoth-mountain.jpg';
-- Marquette Mountain: was "Rickdrew at English Wikipedia / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Rickdrew at English Wikipedia / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Marquette-ski1.jpg', updated_at = now() WHERE slug = 'marquette-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/marquette-mountain.jpg';
-- Mohawk Mountain Ski Area: was "Jrclark (talk) / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Jrclark at English Wikipedia / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:MohawkMountain.jpg', updated_at = now() WHERE slug = 'mohawk-mountain-ski-area' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mohawk-mountain-ski-area.jpg';
-- Monarch Mountain: was "EpicV27 / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'EpicV27 / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Monarch_Ski_Resort.jpg', updated_at = now() WHERE slug = 'monarch-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/monarch-mountain.jpg';
-- Mont Ripley: was "Chris857 / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Chris857 / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Mont_Ripley_in_Winter.jpg', updated_at = now() WHERE slug = 'mont-ripley' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mont-ripley.jpg';
-- Montage Mountain: was "Ekem / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Ekem / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Montage.mountain.ski.1.JPG', updated_at = now() WHERE slug = 'montage-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/montage-mountain.jpg';
-- Montana Snowbowl: was "Evan Lovely / CC BY-SA 2.0"
UPDATE resorts SET hero_image_attribution = 'Evan Lovely / CC BY-SA 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Snowbowl%27s_Bowl.jpg', updated_at = now() WHERE slug = 'montana-snowbowl' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/montana-snowbowl.jpg';
-- Mount Snow: was "William J Sisti from Morristown, NJ, USA / CC BY-SA 2.0"
UPDATE resorts SET hero_image_attribution = 'William J Sisti from Morristown, NJ, USA / CC BY-SA 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Freefall_(3256829416).jpg', updated_at = now() WHERE slug = 'mount-snow' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mount-snow.jpg';
-- Mt. Brighton: was "Codepro at English Wikipedia / CC BY-SA 2.5"
UPDATE resorts SET hero_image_attribution = 'Codepro at English Wikipedia / CC BY-SA 2.5', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Mt._Brighton_Ski_Hill.jpg', updated_at = now() WHERE slug = 'mt-brighton' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mt-brighton.jpg';
-- Mt La Crosse: was "Wikideas1 / CC0"
UPDATE resorts SET hero_image_attribution = 'Wikideas1 / CC0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Mt._La_Crosse.jpg', updated_at = now() WHERE slug = 'mt-la-crosse' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mt-la-crosse.jpg';
-- Mt. Shasta Ski Park: was "Digitalskipark / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Digitalskipark / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Mt_shasta_ski_park.jpg', updated_at = now() WHERE slug = 'mt-shasta-ski-park' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/mt-shasta-ski-park.jpg';
-- Nashoba Valley Ski Area: was "John Phelan / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'John Phelan / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Nashoba_Valley_Ski_Area,_Westford_MA.jpg', updated_at = now() WHERE slug = 'nashoba-valley-ski-area' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/nashoba-valley-ski-area.jpg';
-- Northeast Slopes: was "Redjar / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Redjar / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Northeast_slopes_ski_area_aerial.jpg', updated_at = now() WHERE slug = 'northeast-slopes' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/northeast-slopes.jpg';
-- Northstar California: was "Leijurv / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Leijurv / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Northstar_California_East_Ridge_2019.jpg', updated_at = now() WHERE slug = 'northstar-california' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/northstar-california.jpg';
-- Nub's Nob: was "Mr Swordfish2 / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Mr Swordfish2 / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:NubsNob.jpg', updated_at = now() WHERE slug = 'nubs-nob' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/nubs-nob.jpg';
-- Okemo Mountain Resort: was "Jrclark (talk) / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Jrclark at English Wikipedia / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Okemo-2005-0316a.jpg', updated_at = now() WHERE slug = 'okemo-mountain-resort' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/okemo-mountain-resort.jpg';
-- Park City Mountain Resort: was "Rudi Riet from Washington, DC, United States / CC BY-SA 2.0"
UPDATE resorts SET hero_image_attribution = 'Rudi Riet from Washington, DC, United States / CC BY-SA 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Eagle_Race_Arena_at_Park_City_Resort.jpg', updated_at = now() WHERE slug = 'park-city' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/park-city.jpg';
-- Perfect North Slopes: was "Serge Melki / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'Serge Melki / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Perfect_North_Slopes-_III_(3245557441).jpg', updated_at = now() WHERE slug = 'perfect-north' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/perfect-north.jpg';
-- Plattekill Mountain: was "Rosst7200 / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Rosst7200 / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Fullsizeoutput_41a.jpg', updated_at = now() WHERE slug = 'plattekill-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/plattekill-mountain.jpg';
-- Powder Mountain: was "Baileypalblue / Public domain"
UPDATE resorts SET hero_image_attribution = 'Baileypalblue / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Powder_Mountain_Paradise_Lift.JPG', updated_at = now() WHERE slug = 'powder-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/powder-mountain.jpg';
-- Powder Ridge Mountain Park & Resort: was "Morrowlong / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Morrowlong / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Powder_Ridge_Park._Looking_down_the_Middlefield_slope.jpg', updated_at = now() WHERE slug = 'powder-ridge-mountain-park' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/powder-ridge-mountain-park.jpg';
-- Red Lodge Mountain: was "Elkman / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Elkman / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Red_Lodge_Palisades.jpg', updated_at = now() WHERE slug = 'red-lodge' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/red-lodge.jpg';
-- Saddleback: was "Bubblecuffer / Public domain"
UPDATE resorts SET hero_image_attribution = 'Bubblecuffer / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Saddleback_2009_Kennebago_Top_Terminal.jpg', updated_at = now() WHERE slug = 'saddleback' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/saddleback.jpg';
-- Shawnee Mountain Ski Area: was "Trolley8 / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Trolley8 / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Partek_Ski_Lift_at_Shawnee_Mountain,_PA.jpg', updated_at = now() WHERE slug = 'shawnee-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/shawnee-mountain.jpg';
-- Silverton Mountain: was "Zach Dischner / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'Zach Dischner / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Dropping_In_Silverton_Mountain.jpg', updated_at = now() WHERE slug = 'silverton-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/silverton-mountain.jpg';
-- Ski Apache: was "Jonathan Cutrer from San Angelo, Texas, United States / CC BY 2.0"
UPDATE resorts SET hero_image_attribution = 'Jonathan Cutrer from San Angelo, Texas, United States / CC BY 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:The_Slopes_at_Ski_Apache_(49630170923).jpg', updated_at = now() WHERE slug = 'ski-apache' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/ski-apache.jpg';
-- Ski Butternut: was "EgorovaSvetlana / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'EgorovaSvetlana / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Butternut_Ski_Area_and_Tubing_Center_Great_Barrington.jpg', updated_at = now() WHERE slug = 'ski-butternut' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/ski-butternut.jpg';
-- Snow Summit: was "kallahar / CC BY 3.0"
UPDATE resorts SET hero_image_attribution = 'kallahar / CC BY 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Snow_Summit_-_panoramio.jpg', updated_at = now() WHERE slug = 'snow-summit' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/snow-summit.jpg';
-- Snowbasin: was "Kinney / CC BY 3.0"
UPDATE resorts SET hero_image_attribution = 'Kinney / CC BY 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Snowbasin_-_panoramio.jpg', updated_at = now() WHERE slug = 'snowbasin' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/snowbasin.jpg';
-- Snowbird: was "VeggieGarden / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'VeggieGarden / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Snowbird_Tram_at_Hidden_Peak.jpg', updated_at = now() WHERE slug = 'snowbird' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/snowbird.jpg';
-- Spirit Mountain: was "Midnightcomm / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'Midnightcomm / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Spirit_Mountain_ski_area_aerial.jpg', updated_at = now() WHERE slug = 'spirit-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/spirit-mountain.jpg';
-- Steamboat Ski Resort: was "CarTick at English Wikipedia / CC BY-SA 3.0"
UPDATE resorts SET hero_image_attribution = 'CarTick at English Wikipedia / CC BY-SA 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Steamboat_springs_ski_resort.jpg', updated_at = now() WHERE slug = 'steamboat' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/steamboat.jpg';
-- Taos Ski Valley: was "Murray Foubister / CC BY-SA 2.0"
UPDATE resorts SET hero_image_attribution = 'Murray Foubister / CC BY-SA 2.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Taos_Ski_Valley,_New_Mexico_(7334020844).jpg', updated_at = now() WHERE slug = 'taos-ski-valley' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/taos-ski-valley.jpg';
-- Timberline Lodge Ski Area: was "Buidhe / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Buidhe / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Timberline_Lodge_to_Palmer_ski_tour_(8_May_2025)_(30462).jpg', updated_at = now() WHERE slug = 'timberline-lodge' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/timberline-lodge.jpg';
-- Wachusett Mountain: was "ROxBo at English Wikipedia / Public domain"
UPDATE resorts SET hero_image_attribution = 'ROxBo at English Wikipedia / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Wachusett_Mountain_Center.jpg', updated_at = now() WHERE slug = 'wachusett-mountain' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/wachusett-mountain.jpg';
-- Warner Canyon Ski Area: was "Snowsnapper / Public domain"
UPDATE resorts SET hero_image_attribution = 'Snowsnapper / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:WarnerCanyon.JPG', updated_at = now() WHERE slug = 'warner-canyon' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/warner-canyon.jpg';
-- Welch Village: was "Darth Stabro / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Darth Stabro / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Welch_Village_NYE_2020.jpg', updated_at = now() WHERE slug = 'welch-village' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/welch-village.jpg';
-- White Pass Ski Area: was "Goleh / Public domain"
UPDATE resorts SET hero_image_attribution = 'Goleh / Public domain', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:White_Pass_Ski_Area.JPG', updated_at = now() WHERE slug = 'white-pass' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/white-pass.jpg';
-- Whitefish Mountain Resort: was "Donnie Clapp for Whitefish Mountain Resort / CC BY-SA 4.0"
UPDATE resorts SET hero_image_attribution = 'Donnie Clapp for Whitefish Mountain Resort / CC BY-SA 4.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:WhitefishMountainResortAerialView.jpg', updated_at = now() WHERE slug = 'whitefish' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/whitefish.jpg';
-- Woods Valley: was "Russell Lovrin / CC BY 3.0"
UPDATE resorts SET hero_image_attribution = 'Russell Lovrin / CC BY 3.0', hero_image_credit = 'https://commons.wikimedia.org/wiki/File:Woods_Valley_View_of_Delta_Lake,_NY_-_panoramio.jpg', updated_at = now() WHERE slug = 'woods-valley' AND hero_image_url = 'https://yhmzkeeaiknsotydaucs.supabase.co/storage/v1/object/public/resort-heroes/woods-valley.jpg';
