-- Stage 20 — duplicate resort dedupe
-- Generated by scripts/find-dupe-resorts.mjs
-- Pairs: name similarity >= 0.8 (after normalizing 'Ski Area'/'Resort' suffixes)
--        AND great-circle distance <= 5km.
-- Canonical row picked by: most populated columns (richness),
--                          ties broken by shorter slug.
--
-- Active resorts before: 451
-- Rows to deactivate:    9
-- Active resorts after:  442

BEGIN;

-- Cluster: keep 'catamount-ski-area' (Catamount Ski Area, MA)
--   drop 'catamount' — "Catamount Mountain Resort"
-- Cluster: keep 'cooper-spur-area' (Cooper Spur Ski Area, OR)
--   drop 'cooper-spur' — "Cooper Spur Mountain Resort"
-- Cluster: keep 'hoodoo' (Hoodoo, OR)
--   drop 'hoodoo-ski-area' — "Hoodoo Ski Area"
-- Cluster: keep 'mammoth-mountain' (Mammoth Mountain Ski Area, CA)
--   drop 'mammoth' — "Mammoth Mountain"
-- Cluster: keep 'mohawk-mountain-ski-area' (Mohawk Mountain Ski Area, CT)
--   drop 'mohawk' — "Mohawk Mountain"
-- Cluster: keep 'mont-ripley' (Mont Ripley, MI)
--   drop 'mont-ripley-area' — "Mont Ripley Ski Area"
-- Cluster: keep 'mt-la-crosse' (Mt La Crosse, WI)
--   drop 'mount-la-crosse' — "Mount La Crosse"
-- Cluster: keep 'mt-eyak' (Mt Eyak, AK)
--   drop 'mt-eyak-ski-area' — "Mt. Eyak Ski Area"
-- Cluster: keep 'saskadena-six-area' (Saskadena Six Ski Area, VT)
--   drop 'saskadena-six' — "Saskadena Six"

UPDATE resorts SET active = false WHERE slug IN (
  'catamount', 'cooper-spur', 'hoodoo-ski-area', 'mammoth', 'mohawk', 'mont-ripley-area', 'mount-la-crosse', 'mt-eyak-ski-area', 'saskadena-six'
);

COMMIT;
