-- Stage 18 difficulty-mix sync — generated by scripts/process-pct-csvs.mjs
-- Apply via Supabase SQL editor.
-- Source: parallel WebFetch agents, resort sites + Wikipedia, cross-verified.
-- Policy: only HIGH + MEDIUM confidence; LOW (count-derived) → review CSV.
-- Total updates: 90

BEGIN;

-- [HIGH] Snowshoe Mountain
--   note: normalized to 100 from 30/24/27/4 (excl 10% freestyle + 5% glades)
UPDATE resorts SET difficulty_pct_beginner = 35, difficulty_pct_intermediate = 28, difficulty_pct_advanced = 32, difficulty_pct_expert = 5, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'snowshoe-mountain';

-- [HIGH] Steamboat Ski Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 14, difficulty_pct_intermediate = 42, difficulty_pct_advanced = 44, terrain_park_count = 6, has_terrain_park = true WHERE slug = 'steamboat';

-- [HIGH] Stratton Mountain
UPDATE resorts SET difficulty_pct_beginner = 40, difficulty_pct_intermediate = 35, difficulty_pct_advanced = 16, difficulty_pct_expert = 9, terrain_park_count = 7, has_terrain_park = true WHERE slug = 'stratton-mountain';

-- [HIGH] Sunday River
UPDATE resorts SET difficulty_pct_beginner = 33, difficulty_pct_intermediate = 36, difficulty_pct_advanced = 19, difficulty_pct_expert = 12 WHERE slug = 'sunday-river';

-- [HIGH] Sunlight Mountain Resort
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 55, difficulty_pct_advanced = 20, difficulty_pct_expert = 5, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'sunlight-mountain';

-- [HIGH] Waterville Valley
--   note: combined adv/expert
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 59, difficulty_pct_advanced = 26, terrain_park_count = 6, has_terrain_park = true WHERE slug = 'waterville-valley';

-- [HIGH] Whiteface Mountain
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 24, difficulty_pct_intermediate = 46, difficulty_pct_advanced = 30, terrain_park_count = 7, has_terrain_park = true WHERE slug = 'whiteface-mountain';

-- [HIGH] Whitefish Mountain Resort
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 35, difficulty_pct_advanced = 40, difficulty_pct_expert = 10, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'whitefish';

-- [MEDIUM] Alpine Meadows
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 25, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 35, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'alpine-meadows';

-- [MEDIUM] Alta Ski Area
--   note: 3-tier resort, single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 30, difficulty_pct_advanced = 55, terrain_park_count = 0 WHERE slug = 'alta';

-- [MEDIUM] Alyeska Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 11, difficulty_pct_intermediate = 52, difficulty_pct_advanced = 37 WHERE slug = 'alyeska-resort';

-- [MEDIUM] Angel Fire Resort
--   note: 3-tier resort, single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 21, difficulty_pct_intermediate = 56, difficulty_pct_advanced = 23, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'angel-fire-resort';

-- [MEDIUM] Anthony Lakes Mountain Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 38, difficulty_pct_advanced = 42, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'anthony-lakes';

-- [MEDIUM] Arctic Valley Ski Area
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 10, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 50 WHERE slug = 'arctic-valley';

-- [MEDIUM] Arizona Snowbowl
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 37, difficulty_pct_intermediate = 42, difficulty_pct_advanced = 21, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'arizona-snowbowl';

-- [MEDIUM] Bear Valley Mountain Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 25, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 35 WHERE slug = 'bear-valley-mountain';

-- [MEDIUM] Beaver Mountain
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 35, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 25, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'beaver-mountain';

-- [MEDIUM] Big Sky Resort
--   note: single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 25, difficulty_pct_advanced = 60, terrain_park_count = 7, has_terrain_park = true WHERE slug = 'big-sky';

-- [MEDIUM] Blacktail Mountain Ski Area
--   note: 3-tier resort, infobox vs prose discrepancy noted
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 70, difficulty_pct_advanced = 15, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'blacktail';

-- [MEDIUM] Bogus Basin
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 22, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 33, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'bogus-basin';

-- [MEDIUM] Boreal Mountain Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 30, difficulty_pct_intermediate = 55, difficulty_pct_advanced = 15, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'boreal-mountain-resort';

-- [MEDIUM] Bretton Woods
--   note: 3-tier resort, single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 25, difficulty_pct_intermediate = 29, difficulty_pct_advanced = 46, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'bretton-woods';

-- [MEDIUM] Brian Head Resort
UPDATE resorts SET difficulty_pct_beginner = 35, difficulty_pct_intermediate = 35, difficulty_pct_advanced = 20, difficulty_pct_expert = 10 WHERE slug = 'brian-head';

-- [MEDIUM] Brighton Resort
--   note: 3-tier resort, single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 21, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 39, terrain_park_count = 5, has_terrain_park = true WHERE slug = 'brighton';

-- [MEDIUM] Bristol Mountain
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 33, difficulty_pct_intermediate = 49, difficulty_pct_advanced = 18, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'bristol-mountain';

-- [MEDIUM] Bryce Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 33, difficulty_pct_intermediate = 50, difficulty_pct_advanced = 17, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'bryce-resort';

-- [MEDIUM] Cannon Mountain
--   note: 3-tier resort, single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 21, difficulty_pct_intermediate = 47, difficulty_pct_advanced = 32 WHERE slug = 'cannon-mountain';

-- [MEDIUM] Cascade Mountain
--   note: 3-tier resort, single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 38, difficulty_pct_intermediate = 24, difficulty_pct_advanced = 38, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'cascade-mountain';

-- [MEDIUM] Cherry Peak Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 30, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 25, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'cherry-peak';

-- [MEDIUM] Copper Mountain
--   note: wikipedia infobox
UPDATE resorts SET difficulty_pct_beginner = 21, difficulty_pct_intermediate = 25, difficulty_pct_advanced = 36, difficulty_pct_expert = 18 WHERE slug = 'copper-mountain';

-- [MEDIUM] Crested Butte Mountain Resort
--   note: vail-owned; advanced+expert combined (20%)
UPDATE resorts SET difficulty_pct_beginner = 23, difficulty_pct_intermediate = 57, difficulty_pct_advanced = 20 WHERE slug = 'crested-butte';

-- [MEDIUM] Crystal Mountain
--   note: WA; advanced+expert combined (35%); single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 11, difficulty_pct_intermediate = 54, difficulty_pct_advanced = 35, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'crystal-mountain';

-- [MEDIUM] Dartmouth Skiway
--   note: 3-tier resort (novice/intermediate/expert); pct_expert used for top tier
UPDATE resorts SET difficulty_pct_beginner = 25, difficulty_pct_intermediate = 50, difficulty_pct_expert = 25, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'dartmouth-skiway';

-- [MEDIUM] Deer Valley Resort
--   note: 3-tier resort; advanced+expert combined; no terrain parks
UPDATE resorts SET difficulty_pct_beginner = 35, difficulty_pct_intermediate = 44, difficulty_pct_advanced = 21, terrain_park_count = 0 WHERE slug = 'deer-valley';

-- [MEDIUM] Eaglecrest
--   note: single+double black combined; advanced+expert combined
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 40 WHERE slug = 'eaglecrest';

-- [MEDIUM] Eaglecrest Ski Area
--   note: duplicate of eaglecrest; single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 40 WHERE slug = 'eaglecrest-ski-area';

-- [MEDIUM] Eldora Mountain Resort
--   note: 3-tier resort; advanced+expert combined
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 50, difficulty_pct_advanced = 30, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'eldora';

-- [MEDIUM] Giants Ridge
--   note: 3-tier resort; advanced+expert combined
UPDATE resorts SET difficulty_pct_beginner = 30, difficulty_pct_intermediate = 50, difficulty_pct_advanced = 20, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'giants-ridge';

-- [MEDIUM] Grand Targhee Resort
--   note: wikipedia infobox
UPDATE resorts SET difficulty_pct_beginner = 10, difficulty_pct_intermediate = 70, difficulty_pct_advanced = 15, difficulty_pct_expert = 5, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'grand-targhee';

-- [MEDIUM] Granite Gorge
--   note: 3-tier resort (novice/intermediate/expert); pct sums to 103
UPDATE resorts SET difficulty_pct_beginner = 39, difficulty_pct_intermediate = 16, difficulty_pct_expert = 48, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'granite-gorge';

-- [MEDIUM] Gunstock Mountain Resort
--   note: 3-tier resort (novice/intermediate/expert); pct_expert used for top tier
UPDATE resorts SET difficulty_pct_beginner = 12, difficulty_pct_intermediate = 61, difficulty_pct_expert = 27, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'gunstock-mountain-resort';

-- [MEDIUM] Heavenly Mountain Resort
--   note: vail-owned; 3-tier resort; advanced+expert combined
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 35, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'heavenly-mountain-resort';

-- [MEDIUM] Homewood Mountain Resort
--   note: 3-tier resort; advanced+expert combined
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 50, difficulty_pct_advanced = 35, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'homewood-mountain-resort';

-- [MEDIUM] Hoodoo
--   note: 3-tier resort (easiest/difficult/most-difficult); pct_expert used for top tier
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 39, difficulty_pct_expert = 41 WHERE slug = 'hoodoo';

-- [MEDIUM] Hoodoo Ski Area
--   note: duplicate of hoodoo; 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 39, difficulty_pct_expert = 41 WHERE slug = 'hoodoo-ski-area';

-- [MEDIUM] June Mountain
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 45, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'june-mountain';

-- [MEDIUM] Keystone Resort
--   note: vail-owned; single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 19, difficulty_pct_intermediate = 32, difficulty_pct_advanced = 49, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'keystone';

-- [MEDIUM] Killington
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 28, difficulty_pct_intermediate = 33, difficulty_pct_advanced = 39, terrain_park_count = 5, has_terrain_park = true WHERE slug = 'killington';

-- [MEDIUM] Kirkwood Mountain Resort
--   note: vail-owned; single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 12, difficulty_pct_intermediate = 30, difficulty_pct_advanced = 58, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'kirkwood-mountain-resort';

-- [MEDIUM] Lee Canyon
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 40, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'lee-canyon';

-- [MEDIUM] Lost Trail Powder Mountain
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 60, difficulty_pct_advanced = 20, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'lost-trail';

-- [MEDIUM] Mammoth Mountain
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 48, difficulty_pct_advanced = 37, terrain_park_count = 8, has_terrain_park = true WHERE slug = 'mammoth';

-- [MEDIUM] Mammoth Mountain Ski Area
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 48, difficulty_pct_advanced = 37, terrain_park_count = 8, has_terrain_park = true WHERE slug = 'mammoth-mountain';

-- [MEDIUM] Marquette Mountain
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 15, difficulty_pct_intermediate = 50, difficulty_pct_advanced = 35, terrain_park_count = 0 WHERE slug = 'marquette-mountain';

-- [MEDIUM] Mt. Brighton
--   note: vail-owned; 3-tier resort; single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 30, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 30, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'mt-brighton';

-- [MEDIUM] Mt. Hood Skibowl
--   note: 3-tier resort; terrain park count not specified
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 40 WHERE slug = 'mt-hood-skibowl';

-- [MEDIUM] Mt. Spokane Ski and Snowboard Park
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 23, difficulty_pct_intermediate = 62, difficulty_pct_advanced = 15, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'mt-spokane';

-- [MEDIUM] Nordic Valley
--   note: 3-tier resort; now Wolf Mountain; single+double black combined
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 30, difficulty_pct_advanced = 50, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'nordic-valley';

-- [MEDIUM] Paoli Peaks
--   note: vail-owned 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 25, difficulty_pct_intermediate = 55, difficulty_pct_advanced = 20, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'paoli-peaks';

-- [MEDIUM] Park City Mountain Resort
--   note: vail-owned 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 7, difficulty_pct_intermediate = 49, difficulty_pct_advanced = 44, terrain_park_count = 7, has_terrain_park = true WHERE slug = 'park-city';

-- [MEDIUM] Pomerelle Mountain Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 50, difficulty_pct_advanced = 30 WHERE slug = 'pomerelle';

-- [MEDIUM] Powder Ridge Mountain Park & Resort
--   note: 3-tier resort with terrain park
UPDATE resorts SET difficulty_pct_beginner = 42, difficulty_pct_intermediate = 37, difficulty_pct_advanced = 21, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'powder-ridge-mountain-park';

-- [MEDIUM] Powderhorn Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 50, difficulty_pct_advanced = 30, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'powderhorn';

-- [MEDIUM] Silverton Mountain
--   note: expert-only resort 0 terrain parks per wiki
UPDATE resorts SET difficulty_pct_beginner = 0, difficulty_pct_intermediate = 0, difficulty_pct_advanced = 0, difficulty_pct_expert = 100, terrain_park_count = 0 WHERE slug = 'silverton-mountain';

-- [MEDIUM] Snow Summit
--   note: low int+int combined to int per wiki
UPDATE resorts SET difficulty_pct_beginner = 10, difficulty_pct_intermediate = 65, difficulty_pct_advanced = 25 WHERE slug = 'snow-summit';

-- [MEDIUM] Snowhaven
--   note: 2-tier resort
UPDATE resorts SET difficulty_pct_beginner = 75, difficulty_pct_intermediate = 25, terrain_park_count = 0 WHERE slug = 'snowhaven';

-- [MEDIUM] Soda Springs Mountain Resort
--   note: 3-tier resort sums 101
UPDATE resorts SET difficulty_pct_beginner = 53, difficulty_pct_intermediate = 16, difficulty_pct_advanced = 32 WHERE slug = 'soda-springs';

-- [MEDIUM] Soldier Mountain
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 28, difficulty_pct_intermediate = 25, difficulty_pct_advanced = 47, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'soldier-mountain';

-- [MEDIUM] Solitude Mountain Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 10, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 50 WHERE slug = 'solitude';

-- [MEDIUM] Spout Springs Ski Area
--   note: 3-tier resort no terrain parks
UPDATE resorts SET difficulty_pct_beginner = 35, difficulty_pct_intermediate = 35, difficulty_pct_advanced = 30, terrain_park_count = 0 WHERE slug = 'spout-springs';

-- [MEDIUM] Stevens Pass
--   note: vail-owned 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 11, difficulty_pct_intermediate = 54, difficulty_pct_advanced = 35, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'stevens-pass';

-- [MEDIUM] Stowe Mountain Resort
--   note: vail-owned 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 16, difficulty_pct_intermediate = 55, difficulty_pct_advanced = 30, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'stowe-mountain-resort';

-- [MEDIUM] Sugar Bowl Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 17, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 38 WHERE slug = 'sugar-bowl-resort';

-- [MEDIUM] Sugar Mountain Resort
--   note: 3-tier resort - resort labels hardest as Expert mapped to advanced
UPDATE resorts SET difficulty_pct_beginner = 40, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 20 WHERE slug = 'sugar-mountain-resort';

-- [MEDIUM] Sun Valley Resort
--   note: Bald Mtn only; note relative ratings
UPDATE resorts SET difficulty_pct_beginner = 36, difficulty_pct_intermediate = 42, difficulty_pct_advanced = 20, difficulty_pct_expert = 2 WHERE slug = 'sun-valley';

-- [MEDIUM] Sundance Mountain Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 40, difficulty_pct_advanced = 40, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'sundance';

-- [MEDIUM] Sunrise Park Resort
--   note: combined adv/expert as advanced
UPDATE resorts SET difficulty_pct_beginner = 46, difficulty_pct_intermediate = 28, difficulty_pct_advanced = 25, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'sunrise-park-resort';

-- [MEDIUM] Tahoe Donner Downhill Ski Area
--   note: beginner/intermediate only resort
UPDATE resorts SET difficulty_pct_beginner = 40, difficulty_pct_intermediate = 60, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'tahoe-donner-downhill';

-- [MEDIUM] Tamarack Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 17, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 38, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'tamarack';

-- [MEDIUM] Taos Ski Valley
--   note: combined adv/expert as advanced
UPDATE resorts SET difficulty_pct_beginner = 24, difficulty_pct_intermediate = 25, difficulty_pct_advanced = 51, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'taos-ski-valley';

-- [MEDIUM] Telluride Ski Resort
--   note: combined adv/expert as advanced
UPDATE resorts SET difficulty_pct_beginner = 23, difficulty_pct_intermediate = 36, difficulty_pct_advanced = 41, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'telluride';

-- [MEDIUM] The Summit at Snoqualmie
--   note: 3-tier resort; combined adv/expert
UPDATE resorts SET difficulty_pct_beginner = 14, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 41 WHERE slug = 'the-summit-at-snoqualmie';

-- [MEDIUM] Thunder Ridge Ski Area
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 48, difficulty_pct_intermediate = 19, difficulty_pct_advanced = 33, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'thunder-ridge-ski-area';

-- [MEDIUM] Timberline Lodge Ski Area
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 50, difficulty_pct_advanced = 30 WHERE slug = 'timberline-lodge';

-- [MEDIUM] Vail Ski Resort
--   note: vail-owned; 3-tier; combined adv/expert
UPDATE resorts SET difficulty_pct_beginner = 18, difficulty_pct_intermediate = 29, difficulty_pct_advanced = 53, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'vail';

-- [MEDIUM] Wildcat Mountain
--   note: vail-owned; 3-tier
UPDATE resorts SET difficulty_pct_beginner = 25, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 30, terrain_park_count = 0 WHERE slug = 'wildcat-mountain';

-- [MEDIUM] Willamette Pass Resort
--   note: combined adv/expert
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 45, difficulty_pct_advanced = 35, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'willamette-pass';

-- [MEDIUM] Winter Park Resort
--   note: combined most-difficult+expert as expert (52+3)
UPDATE resorts SET difficulty_pct_beginner = 8, difficulty_pct_intermediate = 18, difficulty_pct_advanced = 19, difficulty_pct_expert = 55 WHERE slug = 'winter-park';

-- [MEDIUM] Wintergreen Resort
--   note: 3-tier resort
UPDATE resorts SET difficulty_pct_beginner = 23, difficulty_pct_intermediate = 35, difficulty_pct_advanced = 42, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'wintergreen-resort';

-- [MEDIUM] Wolf Creek Ski Area
UPDATE resorts SET difficulty_pct_beginner = 20, difficulty_pct_intermediate = 35, difficulty_pct_advanced = 25, difficulty_pct_expert = 20 WHERE slug = 'wolf-creek';

COMMIT;
