-- Trail breakdown sync — generated by scripts/process-trail-csvs.mjs
-- Apply via Supabase SQL editor (https://supabase.com/dashboard/project/yhmzkeeaiknsotydaucs/sql/new)
-- Source: parallel WebFetch agents, Wikipedia + resort sites, cross-verified.
-- Policy: only HIGH + MEDIUM confidence; LOW (% derived) saved to data/trail-breakdown-review.csv for manual review.
--
-- Total updates: 86

BEGIN;

-- [HIGH] Aspen Highlands
--   note: wikipedia infobox explicit counts
UPDATE resorts SET trails_beginner = 0, trails_intermediate = 23, trails_advanced = 12, trails_expert = 65, terrain_park_count = 0 WHERE slug = 'aspen-highlands';

-- [HIGH] Aspen Mountain
--   note: wikipedia infobox explicit counts; no green runs
UPDATE resorts SET trails_beginner = 0, trails_intermediate = 48, trails_advanced = 26, trails_expert = 26, terrain_park_count = 0 WHERE slug = 'aspen-mountain';

-- [HIGH] Aspen Snowmass
--   note: wikipedia snowmass entity; aspen-snowmass is the multi-resort brand
UPDATE resorts SET trails_beginner = 6, trails_intermediate = 47, trails_advanced = 17, trails_expert = 30, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'aspen-snowmass';

-- [HIGH] Bottineau Winter Park
--   note: wikipedia infobox explicit counts
UPDATE resorts SET trails_beginner = 2, trails_intermediate = 3, trails_advanced = 4, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'bottineau-winter-park';

-- [HIGH] Buck Hill
--   note: wikipedia infobox explicit counts
UPDATE resorts SET trails_beginner = 6, trails_intermediate = 6, trails_advanced = 4 WHERE slug = 'buck-hill';

-- [HIGH] Chestnut Mountain Resort
--   note: wikipedia infobox explicit counts
UPDATE resorts SET trails_beginner = 4, trails_intermediate = 11, trails_advanced = 3, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'chestnut-mountain';

-- [HIGH] Greek Peak
--   note: wiki gives explicit counts including expert
UPDATE resorts SET trails_beginner = 20, trails_intermediate = 16, trails_advanced = 14, trails_expert = 5, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'greek-peak';

-- [HIGH] Hyland Hills Ski Area
--   note: wiki explicit counts
UPDATE resorts SET trails_beginner = 3, trails_intermediate = 4, trails_advanced = 4, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'hyland-hills';

-- [HIGH] Indianhead Mountain
--   note: now part of snowriver; jackson creek summit data
UPDATE resorts SET trails_beginner = 10, trails_intermediate = 7, trails_advanced = 7, trails_expert = 4, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'indianhead-mountain';

-- [HIGH] Lutsen Mountains
--   note: wikipedia infobox exact counts
UPDATE resorts SET trails_beginner = 18, trails_intermediate = 47, trails_advanced = 25, trails_expert = 10, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'lutsen-mountains';

-- [HIGH] Magic Mountain
--   note: wikipedia exact trail counts by category
UPDATE resorts SET trails_beginner = 11, trails_intermediate = 14, trails_advanced = 10, trails_expert = 4, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'magic-mountain';

-- [HIGH] Mont Ripley
--   note: derived from 16/35/42/6% of 31 trails
UPDATE resorts SET trails_beginner = 5, trails_intermediate = 11, trails_advanced = 13, trails_expert = 2, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'mont-ripley';

-- [HIGH] Mont Ripley Ski Area
--   note: derived from 16/35/42/6% of 31 trails
UPDATE resorts SET trails_beginner = 5, trails_intermediate = 11, trails_advanced = 13, trails_expert = 2, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'mont-ripley-area';

-- [HIGH] Mt. Abram
--   note: wikipedia exact counts; single+double black combined as expert; 0 parks
UPDATE resorts SET trails_beginner = 10, trails_intermediate = 21, trails_advanced = 13, terrain_park_count = 0 WHERE slug = 'mt-abram';

-- [HIGH] Mt. Bachelor
--   note: derived from 15/35/30/20% of 101 trails
UPDATE resorts SET trails_beginner = 15, trails_intermediate = 35, trails_advanced = 30, trails_expert = 20, terrain_park_count = 15, has_terrain_park = true WHERE slug = 'mt-bachelor';

-- [HIGH] Mt. Hood Meadows
--   note: derived from 15/40/15/30% of 87 trails
UPDATE resorts SET trails_beginner = 13, trails_intermediate = 35, trails_advanced = 13, trails_expert = 26, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'mt-hood-meadows';

-- [HIGH] Nashoba Valley Ski Area
--   note: wikipedia exact named trail counts; 3-tier
UPDATE resorts SET trails_beginner = 4, trails_intermediate = 8, trails_advanced = 5, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'nashoba-valley-ski-area';

-- [HIGH] Snowbasin
--   note: wiki gives explicit count: 7 easier/30 more difficult/35 most difficult/32 expert only
UPDATE resorts SET trails_beginner = 7, trails_intermediate = 30, trails_advanced = 35, trails_expert = 32, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'snowbasin';

-- [HIGH] Snowmass
--   note: wiki infobox explicit count: 6 green/47 blue/17 black/30 double black
UPDATE resorts SET trails_beginner = 6, trails_intermediate = 47, trails_advanced = 17, trails_expert = 30, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'snowmass';

-- [HIGH] Timberline Mountain
--   note: wikipedia infobox explicit counts
UPDATE resorts SET trails_beginner = 9, trails_intermediate = 6, trails_advanced = 4, trails_expert = 2, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'timberline-mountain';

-- [MEDIUM] Arapahoe Basin
--   note: derived from 7/20/49/24% of 145
UPDATE resorts SET trails_beginner = 10, trails_intermediate = 29, trails_advanced = 71, trails_expert = 35, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'arapahoe-basin';

-- [MEDIUM] Big Boulder
--   note: vail-owned; wikipedia gives 18 trails 2 parks but no difficulty breakdown
UPDATE resorts SET terrain_park_count = 2, has_terrain_park = true WHERE slug = 'big-boulder';

-- [MEDIUM] Big Snow American Dream
--   note: wikipedia infobox explicit
UPDATE resorts SET trails_beginner = 1, trails_intermediate = 1, trails_advanced = 1, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'big-snow-american-dream';

-- [MEDIUM] Blue Hills Ski Area
--   note: wikipedia operations section gives explicit counts
UPDATE resorts SET trails_beginner = 6, trails_intermediate = 5, trails_advanced = 4 WHERE slug = 'blue-hills-ski-area';

-- [MEDIUM] Breckenridge Ski Resort
--   note: vail-owned; derived from 14/31/19/36% of 187; terrain parks listed as 25 acres not count
UPDATE resorts SET trails_beginner = 26, trails_intermediate = 58, trails_advanced = 36, trails_expert = 67 WHERE slug = 'breckenridge';

-- [MEDIUM] Burke Mountain
--   note: derived from 11/47/33/9% of 55
UPDATE resorts SET trails_beginner = 6, trails_intermediate = 26, trails_advanced = 18, trails_expert = 5, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'burke-mountain';

-- [MEDIUM] Buttermilk
--   note: derived from 35/39/26/0% of 44
UPDATE resorts SET trails_beginner = 15, trails_intermediate = 17, trails_advanced = 11, trails_expert = 0, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'buttermilk';

-- [MEDIUM] Camelback Mountain Resort
--   note: derived from 39/26/26/9% of 35
UPDATE resorts SET trails_beginner = 14, trails_intermediate = 9, trails_advanced = 9, trails_expert = 3, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'camelback-mountain-resort';

-- [MEDIUM] Catamount Mountain Resort
--   note: wikipedia explicit counts
UPDATE resorts SET trails_beginner = 16, trails_intermediate = 17, trails_advanced = 7, trails_expert = 2, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'catamount';

-- [MEDIUM] Crystal Mountain
--   note: 58 trails no difficulty breakdown
UPDATE resorts SET terrain_park_count = 3, has_terrain_park = true WHERE slug = 'crystal';

-- [MEDIUM] Devil's Head Resort
--   note: 30 trails no difficulty breakdown
UPDATE resorts SET terrain_park_count = 3, has_terrain_park = true WHERE slug = 'devils-head';

-- [MEDIUM] Donner Ski Ranch
--   note: wiki gives explicit counts
UPDATE resorts SET trails_beginner = 16, trails_intermediate = 20, trails_advanced = 16 WHERE slug = 'donner-ski-ranch';

-- [MEDIUM] Eaton Mountain
--   note: wiki gives explicit counts; expert mapped to advanced
UPDATE resorts SET trails_beginner = 5, trails_intermediate = 7, trails_advanced = 6, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'eaton-mountain';

-- [MEDIUM] Echo Mountain
--   note: wiki explicit counts
UPDATE resorts SET trails_beginner = 3, trails_intermediate = 6, trails_advanced = 4 WHERE slug = 'echo-mountain';

-- [MEDIUM] Frost Fire Park
--   note: wiki explicit counts
UPDATE resorts SET trails_beginner = 4, trails_intermediate = 3, trails_advanced = 3, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'frost-fire-park';

-- [MEDIUM] Gore Mountain
--   note: 110 trails no difficulty breakdown
UPDATE resorts SET terrain_park_count = 4, has_terrain_park = true WHERE slug = 'gore-mountain';

-- [MEDIUM] Granite Peak Ski Area
--   note: 58 trails no breakdown
UPDATE resorts SET terrain_park_count = 4, has_terrain_park = true WHERE slug = 'granite-peak';

-- [MEDIUM] Great Bear Recreation Park
--   note: 14 trails no breakdown
UPDATE resorts SET terrain_park_count = 1, has_terrain_park = true WHERE slug = 'great-bear';

-- [MEDIUM] Great Bear Ski Valley
--   note: duplicate entry; same as great-bear
UPDATE resorts SET terrain_park_count = 1, has_terrain_park = true WHERE slug = 'great-bear-valley';

-- [MEDIUM] Hatley Pointe
--   note: wiki explicit counts
UPDATE resorts SET trails_beginner = 4, trails_intermediate = 8, trails_advanced = 3, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'hatley-pointe';

-- [MEDIUM] Hidden Valley (PA)
--   note: vail-owned; 26 trails no breakdown
UPDATE resorts SET terrain_park_count = 2, has_terrain_park = true WHERE slug = 'hidden-valley';

-- [MEDIUM] Holiday Valley
--   note: wiki trails table 15 easier 15 more diff 11 most diff 5 extreme; 5 terrain parks
UPDATE resorts SET trails_beginner = 15, trails_intermediate = 15, trails_advanced = 11, trails_expert = 5, terrain_park_count = 5, has_terrain_park = true WHERE slug = 'holiday-valley';

-- [MEDIUM] Hurricane Ridge Ski and Snowboard Area
--   note: 10 trails no breakdown
UPDATE resorts SET terrain_park_count = 1, has_terrain_park = true WHERE slug = 'hurricane-ridge';

-- [MEDIUM] Jiminy Peak
--   note: 45 trails no breakdown
UPDATE resorts SET terrain_park_count = 3, has_terrain_park = true WHERE slug = 'jiminy-peak';

-- [MEDIUM] King Pine
--   note: derived from 44/31/25% of 17 trails
UPDATE resorts SET trails_beginner = 7, trails_intermediate = 5, trails_advanced = 4, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'king-pine';

-- [MEDIUM] Laurel Mountain
--   note: vail-owned; 3-tier (no expert)
UPDATE resorts SET trails_beginner = 10, trails_intermediate = 7, trails_advanced = 3 WHERE slug = 'laurel-mountain';

-- [MEDIUM] Liberty Mountain
--   note: vail-owned; derived from 27/41/14/18% of 22 trails
UPDATE resorts SET trails_beginner = 6, trails_intermediate = 9, trails_advanced = 3, trails_expert = 4, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'liberty-mountain';

-- [MEDIUM] Little Switzerland
--   note: 18 total runs but no difficulty breakdown; 3 terrain parks
UPDATE resorts SET terrain_park_count = 3, has_terrain_park = true WHERE slug = 'little-switzerland';

-- [MEDIUM] Lookout Pass Ski and Recreation Area
--   note: derived from 14/42/42/2% of 52 trails
UPDATE resorts SET trails_beginner = 7, trails_intermediate = 22, trails_advanced = 22, trails_expert = 1, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'lookout-pass';

-- [MEDIUM] Loon Mountain
--   note: derived from 19/53/28% of 73 trails; 3-tier wikipedia
UPDATE resorts SET trails_beginner = 14, trails_intermediate = 39, trails_advanced = 20, terrain_park_count = 6, has_terrain_park = true WHERE slug = 'loon-mountain';

-- [MEDIUM] Loveland Ski Area
--   note: derived from 13/41/46% of 94 trails; adv+exp combined
UPDATE resorts SET trails_beginner = 12, trails_intermediate = 39, trails_advanced = 43, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'loveland';

-- [MEDIUM] Montage Mountain
--   note: derived from 19/46/19/15% of ~26 trails
UPDATE resorts SET trails_beginner = 5, trails_intermediate = 12, trails_advanced = 5, trails_expert = 4, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'montage-mountain';

-- [MEDIUM] Moose Mountain (Skiland)
--   note: derived from 20/50/30% of 46 trails; 3-tier wiki
UPDATE resorts SET trails_beginner = 9, trails_intermediate = 23, trails_advanced = 14 WHERE slug = 'skiland';

-- [MEDIUM] Mount Snow
--   note: vail-owned; derived from 16/66/17/1% of 86 trails
UPDATE resorts SET trails_beginner = 14, trails_intermediate = 57, trails_advanced = 15, trails_expert = 1, terrain_park_count = 10, has_terrain_park = true WHERE slug = 'mount-snow';

-- [MEDIUM] Mount Sunapee
--   note: vail-owned; derived from 26/48/26% of 66 trails; 3-tier wiki
UPDATE resorts SET trails_beginner = 17, trails_intermediate = 32, trails_advanced = 17, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'mount-sunapee';

-- [MEDIUM] Mountain High
--   note: derived from 20/42/34/3% of 59 trails; terrain parks Yes but unspecified
UPDATE resorts SET trails_beginner = 12, trails_intermediate = 25, trails_advanced = 20, trails_expert = 2 WHERE slug = 'mountain-high';

-- [MEDIUM] Mt. Baker Ski Area
--   note: derived from 24/45/31% of 31 trails; 3-tier wiki; no terrain park count
UPDATE resorts SET trails_beginner = 7, trails_intermediate = 14, trails_advanced = 10 WHERE slug = 'mt-baker-ski-area';

-- [MEDIUM] Mt. Baldy Ski Resort
--   note: derived from 15/31/54% of 26 trails; 3-tier wiki
UPDATE resorts SET trails_beginner = 4, trails_intermediate = 8, trails_advanced = 14 WHERE slug = 'mt-baldy';

-- [MEDIUM] Mt. Rose Ski Tahoe
--   note: derived from 20/30/40/10% of 70 trails
UPDATE resorts SET trails_beginner = 14, trails_intermediate = 21, trails_advanced = 28, trails_expert = 7, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'mt-rose-ski-tahoe';

-- [MEDIUM] Mt. Shasta
--   note: derived from 20/55/25% of 38 trails; 3-tier wiki
UPDATE resorts SET trails_beginner = 8, trails_intermediate = 21, trails_advanced = 9, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'mt-shasta';

-- [MEDIUM] Mt. Shasta Ski Park
--   note: derived from 20/55/25% of 38 trails; 3-tier wiki
UPDATE resorts SET trails_beginner = 8, trails_intermediate = 21, trails_advanced = 9, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'mt-shasta-ski-park';

-- [MEDIUM] Mt. Waterman
--   note: derived from 20/20/60% of 27 trails; 3-tier wiki; 0 parks
UPDATE resorts SET trails_beginner = 5, trails_intermediate = 5, trails_advanced = 16, terrain_park_count = 0 WHERE slug = 'mt-waterman';

-- [MEDIUM] Northstar California
--   note: vail-owned; derived from 13/60/27% of 100 trails; 3-tier wiki
UPDATE resorts SET trails_beginner = 13, trails_intermediate = 60, trails_advanced = 27, terrain_park_count = 5, has_terrain_park = true WHERE slug = 'northstar-california';

-- [MEDIUM] Ober Mountain
--   note: 3-tier resort (no expert); wikipedia infobox
UPDATE resorts SET trails_beginner = 3, trails_intermediate = 6, trails_advanced = 2, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'ober-mountain';

-- [MEDIUM] Pat's Peak
--   note: derived from wiki 28 trails 50/21/12/17% novice/intermediate/advanced/expert
UPDATE resorts SET trails_beginner = 14, trails_intermediate = 6, trails_advanced = 3, trails_expert = 5, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'pats-peak';

-- [MEDIUM] Perfect North Slopes
--   note: wiki infobox; intermediate includes 1 'advanced intermediate' trail
UPDATE resorts SET trails_beginner = 5, trails_intermediate = 11, trails_advanced = 4, trails_expert = 1, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'perfect-north';

-- [MEDIUM] Plattekill Mountain
--   note: derived from wiki 40 trails with 20/40/20/20% breakdown
UPDATE resorts SET trails_beginner = 8, trails_intermediate = 16, trails_advanced = 8, trails_expert = 8, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'plattekill-mountain';

-- [MEDIUM] Powder Mountain
--   note: derived from wiki 162 trails with 25/40/35% 3-tier
UPDATE resorts SET trails_beginner = 41, trails_intermediate = 65, trails_advanced = 56, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'powder-mountain';

-- [MEDIUM] Purgatory Resort
--   note: derived from wiki 105 trails with 22/35/43% 3-tier
UPDATE resorts SET trails_beginner = 23, trails_intermediate = 37, trails_advanced = 45, terrain_park_count = 6, has_terrain_park = true WHERE slug = 'purgatory';

-- [MEDIUM] Roundtop Mountain Resort
--   note: vail-owned; derived from wiki 22 trails with 29/30/31/10% breakdown
UPDATE resorts SET trails_beginner = 6, trails_intermediate = 7, trails_advanced = 7, trails_expert = 2, terrain_park_count = 4, has_terrain_park = true WHERE slug = 'roundtop-mountain-resort';

-- [MEDIUM] Sandia Peak Ski Area
--   note: derived from wiki 35 trails with 23/49/29% 3-tier
UPDATE resorts SET trails_beginner = 8, trails_intermediate = 17, trails_advanced = 10, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'sandia-peak';

-- [MEDIUM] Seven Springs Mountain Resort
--   note: vail-owned; derived from wiki 40 trails with 35/40/15/10% breakdown
UPDATE resorts SET trails_beginner = 14, trails_intermediate = 16, trails_advanced = 6, trails_expert = 4, terrain_park_count = 7, has_terrain_park = true WHERE slug = 'seven-springs';

-- [MEDIUM] Sierra-at-Tahoe
--   note: derived from wiki 46 trails with 25/50/25% 3-tier
UPDATE resorts SET trails_beginner = 12, trails_intermediate = 23, trails_advanced = 11, terrain_park_count = 6, has_terrain_park = true WHERE slug = 'sierra-at-tahoe';

-- [MEDIUM] Silver Mountain
--   note: derived from wiki 67 trails with 20/40/30/10% breakdown
UPDATE resorts SET trails_beginner = 13, trails_intermediate = 27, trails_advanced = 20, trails_expert = 7 WHERE slug = 'silver-mountain';

-- [MEDIUM] Ski Apache
--   note: derived from wiki 55 trails with 20/60/20% 3-tier
UPDATE resorts SET trails_beginner = 11, trails_intermediate = 33, trails_advanced = 11, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'ski-apache';

-- [MEDIUM] Ski Bluewood
--   note: derived from wiki 24 trails with 27/43/30% 3-tier
UPDATE resorts SET trails_beginner = 7, trails_intermediate = 10, trails_advanced = 7, terrain_park_count = 1, has_terrain_park = true WHERE slug = 'bluewood';

-- [MEDIUM] Ski Bradford
--   note: wiki infobox 3 green/4 blue/8 black; 3-tier; terrain park exists but no count
UPDATE resorts SET trails_beginner = 3, trails_intermediate = 4, trails_advanced = 8 WHERE slug = 'ski-bradford';

-- [MEDIUM] Ski Brule
--   note: wiki body text: 5 green/6 blue/3 black/1 double black; 30-acre 2-trail terrain park
UPDATE resorts SET trails_beginner = 5, trails_intermediate = 6, trails_advanced = 3, trails_expert = 1, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'ski-brule';

-- [MEDIUM] Ski Cooper
--   note: derived from wiki 60 trails with 31/35/34% 3-tier; advanced+expert combined per source
UPDATE resorts SET trails_beginner = 19, trails_intermediate = 21, trails_advanced = 20 WHERE slug = 'ski-cooper';

-- [MEDIUM] Ski Santa Fe
--   note: derived from wiki 88 trails with 20/40/40% 3-tier
UPDATE resorts SET trails_beginner = 18, trails_intermediate = 35, trails_advanced = 35, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'ski-santa-fe';

-- [MEDIUM] Smugglers' Notch
--   note: derived from wiki 78 trails with 19/50/25/6% breakdown
UPDATE resorts SET trails_beginner = 15, trails_intermediate = 39, trails_advanced = 20, trails_expert = 5 WHERE slug = 'smugglers-notch';

-- [MEDIUM] Snow Valley Mountain Resort
--   note: derived from wiki 29 trails with 14/45/31/10% breakdown
UPDATE resorts SET trails_beginner = 4, trails_intermediate = 13, trails_advanced = 9, trails_expert = 3, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'snow-valley';

-- [MEDIUM] Snowbird
--   note: derived from wiki 169 trails with 27/38/35% 3-tier; 0 terrain parks
UPDATE resorts SET trails_beginner = 46, trails_intermediate = 64, trails_advanced = 59, terrain_park_count = 0 WHERE slug = 'snowbird';

-- [MEDIUM] Sugarbush
--   note: explicit counts in infobox; single+double black combined
UPDATE resorts SET trails_beginner = 24, trails_intermediate = 51, trails_advanced = 36 WHERE slug = 'sugarbush';

-- [MEDIUM] Sugarloaf
--   note: wikipedia infobox explicit counts; +superpipe
UPDATE resorts SET trails_beginner = 40, trails_intermediate = 54, trails_advanced = 44, trails_expert = 36, terrain_park_count = 3, has_terrain_park = true WHERE slug = 'sugarloaf';

-- [MEDIUM] Timber Ridge Ski Area
--   note: wikipedia explicit counts; single+double black combined
UPDATE resorts SET trails_beginner = 7, trails_intermediate = 5, trails_advanced = 3, terrain_park_count = 2, has_terrain_park = true WHERE slug = 'timber-ridge';

COMMIT;
